// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "operator_double_div5.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic operator_double_div5::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic operator_double_div5::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> operator_double_div5::ap_ST_fsm_state1 = "1";
const sc_lv<2> operator_double_div5::ap_ST_fsm_state2 = "10";
const sc_lv<32> operator_double_div5::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> operator_double_div5::ap_const_lv1_0 = "0";
const sc_lv<32> operator_double_div5::ap_const_lv32_1 = "1";
const sc_lv<1> operator_double_div5::ap_const_lv1_1 = "1";
const sc_lv<3> operator_double_div5::ap_const_lv3_0 = "000";
const sc_lv<32> operator_double_div5::ap_const_lv32_3F = "111111";
const sc_lv<32> operator_double_div5::ap_const_lv32_34 = "110100";
const sc_lv<32> operator_double_div5::ap_const_lv32_3E = "111110";
const sc_lv<32> operator_double_div5::ap_const_lv32_32 = "110010";
const sc_lv<32> operator_double_div5::ap_const_lv32_33 = "110011";
const sc_lv<2> operator_double_div5::ap_const_lv2_0 = "00";
const sc_lv<11> operator_double_div5::ap_const_lv11_3 = "11";
const sc_lv<11> operator_double_div5::ap_const_lv11_2 = "10";
const sc_lv<11> operator_double_div5::ap_const_lv11_7FF = "11111111111";
const sc_lv<11> operator_double_div5::ap_const_lv11_0 = "00000000000";
const sc_lv<32> operator_double_div5::ap_const_lv32_35 = "110101";
const sc_lv<10> operator_double_div5::ap_const_lv10_0 = "0000000000";
const sc_lv<11> operator_double_div5::ap_const_lv11_1 = "1";
const sc_lv<56> operator_double_div5::ap_const_lv56_2 = "10";
const sc_lv<32> operator_double_div5::ap_const_lv32_36 = "110110";
const sc_lv<32> operator_double_div5::ap_const_lv32_37 = "110111";
const sc_lv<32> operator_double_div5::ap_const_lv32_30 = "110000";
const sc_lv<32> operator_double_div5::ap_const_lv32_2D = "101101";
const sc_lv<32> operator_double_div5::ap_const_lv32_2F = "101111";
const sc_lv<32> operator_double_div5::ap_const_lv32_2A = "101010";
const sc_lv<32> operator_double_div5::ap_const_lv32_2C = "101100";
const sc_lv<32> operator_double_div5::ap_const_lv32_27 = "100111";
const sc_lv<32> operator_double_div5::ap_const_lv32_29 = "101001";
const sc_lv<32> operator_double_div5::ap_const_lv32_24 = "100100";
const sc_lv<32> operator_double_div5::ap_const_lv32_26 = "100110";
const sc_lv<32> operator_double_div5::ap_const_lv32_21 = "100001";
const sc_lv<32> operator_double_div5::ap_const_lv32_23 = "100011";
const sc_lv<32> operator_double_div5::ap_const_lv32_1E = "11110";
const sc_lv<32> operator_double_div5::ap_const_lv32_20 = "100000";
const sc_lv<32> operator_double_div5::ap_const_lv32_1B = "11011";
const sc_lv<32> operator_double_div5::ap_const_lv32_1D = "11101";
const sc_lv<32> operator_double_div5::ap_const_lv32_18 = "11000";
const sc_lv<32> operator_double_div5::ap_const_lv32_1A = "11010";
const sc_lv<32> operator_double_div5::ap_const_lv32_15 = "10101";
const sc_lv<32> operator_double_div5::ap_const_lv32_17 = "10111";
const sc_lv<32> operator_double_div5::ap_const_lv32_12 = "10010";
const sc_lv<32> operator_double_div5::ap_const_lv32_14 = "10100";
const sc_lv<32> operator_double_div5::ap_const_lv32_F = "1111";
const sc_lv<32> operator_double_div5::ap_const_lv32_11 = "10001";
const sc_lv<32> operator_double_div5::ap_const_lv32_C = "1100";
const sc_lv<32> operator_double_div5::ap_const_lv32_E = "1110";
const sc_lv<32> operator_double_div5::ap_const_lv32_9 = "1001";
const sc_lv<32> operator_double_div5::ap_const_lv32_B = "1011";
const sc_lv<32> operator_double_div5::ap_const_lv32_6 = "110";
const sc_lv<32> operator_double_div5::ap_const_lv32_8 = "1000";
const sc_lv<32> operator_double_div5::ap_const_lv32_3 = "11";
const sc_lv<32> operator_double_div5::ap_const_lv32_5 = "101";
const bool operator_double_div5::ap_const_boolean_1 = true;

operator_double_div5::operator_double_div5(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_lut_div5_chunk_fu_153 = new lut_div5_chunk("grp_lut_div5_chunk_fu_153");
    grp_lut_div5_chunk_fu_153->ap_ready(grp_lut_div5_chunk_fu_153_ap_ready);
    grp_lut_div5_chunk_fu_153->d_V(grp_lut_div5_chunk_fu_153_d_V);
    grp_lut_div5_chunk_fu_153->r_in_V(grp_lut_div5_chunk_fu_153_r_in_V);
    grp_lut_div5_chunk_fu_153->ap_return_0(grp_lut_div5_chunk_fu_153_ap_return_0);
    grp_lut_div5_chunk_fu_153->ap_return_1(grp_lut_div5_chunk_fu_153_ap_return_1);
    grp_lut_div5_chunk_fu_160 = new lut_div5_chunk("grp_lut_div5_chunk_fu_160");
    grp_lut_div5_chunk_fu_160->ap_ready(grp_lut_div5_chunk_fu_160_ap_ready);
    grp_lut_div5_chunk_fu_160->d_V(grp_lut_div5_chunk_fu_160_d_V);
    grp_lut_div5_chunk_fu_160->r_in_V(grp_lut_div5_chunk_fu_153_ap_return_1);
    grp_lut_div5_chunk_fu_160->ap_return_0(grp_lut_div5_chunk_fu_160_ap_return_0);
    grp_lut_div5_chunk_fu_160->ap_return_1(grp_lut_div5_chunk_fu_160_ap_return_1);
    grp_lut_div5_chunk_fu_166 = new lut_div5_chunk("grp_lut_div5_chunk_fu_166");
    grp_lut_div5_chunk_fu_166->ap_ready(grp_lut_div5_chunk_fu_166_ap_ready);
    grp_lut_div5_chunk_fu_166->d_V(grp_lut_div5_chunk_fu_166_d_V);
    grp_lut_div5_chunk_fu_166->r_in_V(grp_lut_div5_chunk_fu_160_ap_return_1);
    grp_lut_div5_chunk_fu_166->ap_return_0(grp_lut_div5_chunk_fu_166_ap_return_0);
    grp_lut_div5_chunk_fu_166->ap_return_1(grp_lut_div5_chunk_fu_166_ap_return_1);
    grp_lut_div5_chunk_fu_172 = new lut_div5_chunk("grp_lut_div5_chunk_fu_172");
    grp_lut_div5_chunk_fu_172->ap_ready(grp_lut_div5_chunk_fu_172_ap_ready);
    grp_lut_div5_chunk_fu_172->d_V(grp_lut_div5_chunk_fu_172_d_V);
    grp_lut_div5_chunk_fu_172->r_in_V(grp_lut_div5_chunk_fu_166_ap_return_1);
    grp_lut_div5_chunk_fu_172->ap_return_0(grp_lut_div5_chunk_fu_172_ap_return_0);
    grp_lut_div5_chunk_fu_172->ap_return_1(grp_lut_div5_chunk_fu_172_ap_return_1);
    grp_lut_div5_chunk_fu_178 = new lut_div5_chunk("grp_lut_div5_chunk_fu_178");
    grp_lut_div5_chunk_fu_178->ap_ready(grp_lut_div5_chunk_fu_178_ap_ready);
    grp_lut_div5_chunk_fu_178->d_V(grp_lut_div5_chunk_fu_178_d_V);
    grp_lut_div5_chunk_fu_178->r_in_V(grp_lut_div5_chunk_fu_172_ap_return_1);
    grp_lut_div5_chunk_fu_178->ap_return_0(grp_lut_div5_chunk_fu_178_ap_return_0);
    grp_lut_div5_chunk_fu_178->ap_return_1(grp_lut_div5_chunk_fu_178_ap_return_1);
    grp_lut_div5_chunk_fu_184 = new lut_div5_chunk("grp_lut_div5_chunk_fu_184");
    grp_lut_div5_chunk_fu_184->ap_ready(grp_lut_div5_chunk_fu_184_ap_ready);
    grp_lut_div5_chunk_fu_184->d_V(grp_lut_div5_chunk_fu_184_d_V);
    grp_lut_div5_chunk_fu_184->r_in_V(grp_lut_div5_chunk_fu_178_ap_return_1);
    grp_lut_div5_chunk_fu_184->ap_return_0(grp_lut_div5_chunk_fu_184_ap_return_0);
    grp_lut_div5_chunk_fu_184->ap_return_1(grp_lut_div5_chunk_fu_184_ap_return_1);
    grp_lut_div5_chunk_fu_190 = new lut_div5_chunk("grp_lut_div5_chunk_fu_190");
    grp_lut_div5_chunk_fu_190->ap_ready(grp_lut_div5_chunk_fu_190_ap_ready);
    grp_lut_div5_chunk_fu_190->d_V(grp_lut_div5_chunk_fu_190_d_V);
    grp_lut_div5_chunk_fu_190->r_in_V(grp_lut_div5_chunk_fu_184_ap_return_1);
    grp_lut_div5_chunk_fu_190->ap_return_0(grp_lut_div5_chunk_fu_190_ap_return_0);
    grp_lut_div5_chunk_fu_190->ap_return_1(grp_lut_div5_chunk_fu_190_ap_return_1);
    grp_lut_div5_chunk_fu_196 = new lut_div5_chunk("grp_lut_div5_chunk_fu_196");
    grp_lut_div5_chunk_fu_196->ap_ready(grp_lut_div5_chunk_fu_196_ap_ready);
    grp_lut_div5_chunk_fu_196->d_V(grp_lut_div5_chunk_fu_196_d_V);
    grp_lut_div5_chunk_fu_196->r_in_V(grp_lut_div5_chunk_fu_190_ap_return_1);
    grp_lut_div5_chunk_fu_196->ap_return_0(grp_lut_div5_chunk_fu_196_ap_return_0);
    grp_lut_div5_chunk_fu_196->ap_return_1(grp_lut_div5_chunk_fu_196_ap_return_1);
    call_ret4_14_i_i_lut_div5_chunk_fu_202 = new lut_div5_chunk("call_ret4_14_i_i_lut_div5_chunk_fu_202");
    call_ret4_14_i_i_lut_div5_chunk_fu_202->ap_ready(call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_ready);
    call_ret4_14_i_i_lut_div5_chunk_fu_202->d_V(p_Result_22_14_i_i_reg_900);
    call_ret4_14_i_i_lut_div5_chunk_fu_202->r_in_V(grp_lut_div5_chunk_fu_196_ap_return_1);
    call_ret4_14_i_i_lut_div5_chunk_fu_202->ap_return_0(call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_0);
    call_ret4_14_i_i_lut_div5_chunk_fu_202->ap_return_1(call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_1);
    call_ret4_15_i_i_lut_div5_chunk_fu_208 = new lut_div5_chunk("call_ret4_15_i_i_lut_div5_chunk_fu_208");
    call_ret4_15_i_i_lut_div5_chunk_fu_208->ap_ready(call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_ready);
    call_ret4_15_i_i_lut_div5_chunk_fu_208->d_V(p_Result_22_15_i_i_reg_905);
    call_ret4_15_i_i_lut_div5_chunk_fu_208->r_in_V(call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_1);
    call_ret4_15_i_i_lut_div5_chunk_fu_208->ap_return_0(call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_0);
    call_ret4_15_i_i_lut_div5_chunk_fu_208->ap_return_1(call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_1);
    call_ret4_16_i_i_lut_div5_chunk_fu_214 = new lut_div5_chunk("call_ret4_16_i_i_lut_div5_chunk_fu_214");
    call_ret4_16_i_i_lut_div5_chunk_fu_214->ap_ready(call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_ready);
    call_ret4_16_i_i_lut_div5_chunk_fu_214->d_V(tmp_9_reg_910);
    call_ret4_16_i_i_lut_div5_chunk_fu_214->r_in_V(call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_1);
    call_ret4_16_i_i_lut_div5_chunk_fu_214->ap_return_0(call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_return_0);
    call_ret4_16_i_i_lut_div5_chunk_fu_214->ap_return_1(call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_return_1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_p_Repl2_s_phi_fu_147_p4);
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( new_mant_V_1_fu_760_p19 );
    sensitive << ( p_Repl2_s_reg_144 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_Result_s_fu_794_p4 );

    SC_METHOD(thread_d_chunk_V_fu_544_p1);
    sensitive << ( p_Result_i_i_fu_534_p4 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_153_d_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( p_Result_22_7_i_i_reg_860 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( d_chunk_V_fu_544_p1 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_153_r_in_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( r_V_ret3_6_i_i_reg_855 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_160_d_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( p_Result_22_8_i_i_reg_865 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_166_d_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( p_Result_22_9_i_i_reg_870 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_172_d_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( p_Result_22_i_i_10_reg_875 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_178_d_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( p_Result_22_10_i_i_reg_880 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_184_d_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( p_Result_22_11_i_i_reg_885 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_190_d_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( p_Result_22_12_i_i_reg_890 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_grp_lut_div5_chunk_fu_196_d_V);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_1_reg_816 );
    sensitive << ( p_Result_22_13_i_i_reg_895 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_icmp4_fu_404_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_8_fu_394_p4 );

    SC_METHOD(thread_icmp_fu_328_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_318_p4 );

    SC_METHOD(thread_new_exp_V_1_fu_354_p2);
    sensitive << ( new_exp_V_fu_300_p4 );
    sensitive << ( shift_V_cast_cast_fu_334_p3 );

    SC_METHOD(thread_new_exp_V_fu_300_p4);
    sensitive << ( p_Val2_s_fu_288_p1 );

    SC_METHOD(thread_new_mant_V_1_fu_760_p19);
    sensitive << ( q_chunk_V_ret2_1_i_i_reg_825 );
    sensitive << ( q_chunk_V_ret2_2_i_i_reg_830 );
    sensitive << ( q_chunk_V_ret2_3_i_i_reg_835 );
    sensitive << ( q_chunk_V_ret2_4_i_i_reg_840 );
    sensitive << ( q_chunk_V_ret2_5_i_i_reg_845 );
    sensitive << ( q_chunk_V_ret2_6_i_i_reg_850 );
    sensitive << ( tmp_10_reg_915 );
    sensitive << ( grp_lut_div5_chunk_fu_153_ap_return_0 );
    sensitive << ( grp_lut_div5_chunk_fu_160_ap_return_0 );
    sensitive << ( grp_lut_div5_chunk_fu_166_ap_return_0 );
    sensitive << ( grp_lut_div5_chunk_fu_172_ap_return_0 );
    sensitive << ( grp_lut_div5_chunk_fu_178_ap_return_0 );
    sensitive << ( grp_lut_div5_chunk_fu_184_ap_return_0 );
    sensitive << ( grp_lut_div5_chunk_fu_190_ap_return_0 );
    sensitive << ( grp_lut_div5_chunk_fu_196_ap_return_0 );
    sensitive << ( call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_0 );
    sensitive << ( call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_0 );
    sensitive << ( call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_return_0 );

    SC_METHOD(thread_new_mant_V_fu_310_p1);
    sensitive << ( p_Val2_s_fu_288_p1 );

    SC_METHOD(thread_p_Repl2_1_fu_374_p3);
    sensitive << ( tmp_7_fu_368_p2 );
    sensitive << ( p_new_exp_V_1_fu_360_p3 );
    sensitive << ( new_exp_V_1_fu_354_p2 );

    SC_METHOD(thread_p_Result_i_i_fu_534_p4);
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_p_Result_s_fu_794_p4);
    sensitive << ( p_Repl2_2_reg_806 );
    sensitive << ( p_Repl2_1_reg_820 );
    sensitive << ( ap_phi_mux_p_Repl2_s_phi_fu_147_p4 );

    SC_METHOD(thread_p_Val2_s_fu_288_p1);
    sensitive << ( in_r );

    SC_METHOD(thread_p_cast_fu_492_p1);
    sensitive << ( xf_V_1_fu_484_p3 );

    SC_METHOD(thread_p_new_exp_V_1_fu_360_p3);
    sensitive << ( tmp_1_fu_342_p2 );

    SC_METHOD(thread_r_V_1_cast_fu_510_p1);
    sensitive << ( r_V_3_fu_504_p2 );

    SC_METHOD(thread_r_V_3_fu_504_p2);
    sensitive << ( xf_V_1_fu_484_p3 );
    sensitive << ( tmp_cast_fu_500_p1 );

    SC_METHOD(thread_r_V_4_fu_514_p2);
    sensitive << ( p_cast_fu_492_p1 );
    sensitive << ( tmp_s_fu_496_p1 );

    SC_METHOD(thread_sel_tmp3_demorgan_fu_422_p2);
    sensitive << ( tmp_4_fu_382_p2 );
    sensitive << ( tmp_5_fu_388_p2 );

    SC_METHOD(thread_sel_tmp3_fu_428_p2);
    sensitive << ( sel_tmp3_demorgan_fu_422_p2 );

    SC_METHOD(thread_sel_tmp4_fu_434_p2);
    sensitive << ( icmp4_fu_404_p2 );
    sensitive << ( sel_tmp3_fu_428_p2 );

    SC_METHOD(thread_sel_tmp7_fu_456_p2);
    sensitive << ( tmp_4_fu_382_p2 );

    SC_METHOD(thread_sel_tmp8_fu_462_p2);
    sensitive << ( tmp_5_fu_388_p2 );
    sensitive << ( sel_tmp7_fu_456_p2 );

    SC_METHOD(thread_shift_V_1_fu_416_p2);
    sensitive << ( new_exp_V_fu_300_p4 );

    SC_METHOD(thread_shift_V_2_fu_440_p3);
    sensitive << ( sel_tmp4_fu_434_p2 );
    sensitive << ( shift_V_fu_410_p2 );
    sensitive << ( shift_V_1_fu_416_p2 );

    SC_METHOD(thread_shift_V_3_fu_448_p3);
    sensitive << ( tmp_4_fu_382_p2 );
    sensitive << ( shift_V_2_fu_440_p3 );

    SC_METHOD(thread_shift_V_4_fu_468_p3);
    sensitive << ( shift_V_cast_cast_fu_334_p3 );
    sensitive << ( sel_tmp8_fu_462_p2 );
    sensitive << ( shift_V_3_fu_448_p3 );

    SC_METHOD(thread_shift_V_cast_cast_fu_334_p3);
    sensitive << ( icmp_fu_328_p2 );

    SC_METHOD(thread_shift_V_fu_410_p2);
    sensitive << ( new_exp_V_fu_300_p4 );

    SC_METHOD(thread_tmp_10_fu_730_p1);
    sensitive << ( grp_lut_div5_chunk_fu_160_ap_return_0 );

    SC_METHOD(thread_tmp_1_fu_342_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( new_exp_V_fu_300_p4 );

    SC_METHOD(thread_tmp_2_fu_348_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( new_exp_V_fu_300_p4 );
    sensitive << ( shift_V_cast_cast_fu_334_p3 );

    SC_METHOD(thread_tmp_3_fu_476_p3);
    sensitive << ( new_mant_V_fu_310_p1 );

    SC_METHOD(thread_tmp_4_fu_382_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( new_exp_V_fu_300_p4 );

    SC_METHOD(thread_tmp_5_fu_388_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( new_exp_V_fu_300_p4 );
    sensitive << ( shift_V_cast_cast_fu_334_p3 );

    SC_METHOD(thread_tmp_7_fu_368_p2);
    sensitive << ( tmp_1_fu_342_p2 );
    sensitive << ( tmp_2_fu_348_p2 );

    SC_METHOD(thread_tmp_8_fu_394_p4);
    sensitive << ( p_Val2_s_fu_288_p1 );

    SC_METHOD(thread_tmp_9_fu_726_p1);
    sensitive << ( xf_V_fu_528_p2 );

    SC_METHOD(thread_tmp_cast_fu_500_p1);
    sensitive << ( shift_V_4_fu_468_p3 );

    SC_METHOD(thread_tmp_fu_318_p4);
    sensitive << ( p_Val2_s_fu_288_p1 );

    SC_METHOD(thread_tmp_s_fu_496_p1);
    sensitive << ( shift_V_4_fu_468_p3 );

    SC_METHOD(thread_xf_V_1_fu_484_p3);
    sensitive << ( tmp_4_fu_382_p2 );
    sensitive << ( xf_V_5_cast_fu_314_p1 );
    sensitive << ( tmp_3_fu_476_p3 );

    SC_METHOD(thread_xf_V_3_fu_520_p3);
    sensitive << ( icmp4_fu_404_p2 );
    sensitive << ( r_V_1_cast_fu_510_p1 );
    sensitive << ( r_V_4_fu_514_p2 );

    SC_METHOD(thread_xf_V_5_cast_fu_314_p1);
    sensitive << ( new_mant_V_fu_310_p1 );

    SC_METHOD(thread_xf_V_fu_528_p2);
    sensitive << ( xf_V_3_fu_520_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "operator_double_div5_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r, "(port)in_r");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_Repl2_2_reg_806, "p_Repl2_2_reg_806");
    sc_trace(mVcdFile, new_mant_V_fu_310_p1, "new_mant_V_fu_310_p1");
    sc_trace(mVcdFile, tmp_1_fu_342_p2, "tmp_1_fu_342_p2");
    sc_trace(mVcdFile, tmp_1_reg_816, "tmp_1_reg_816");
    sc_trace(mVcdFile, p_Repl2_1_fu_374_p3, "p_Repl2_1_fu_374_p3");
    sc_trace(mVcdFile, p_Repl2_1_reg_820, "p_Repl2_1_reg_820");
    sc_trace(mVcdFile, q_chunk_V_ret2_1_i_i_reg_825, "q_chunk_V_ret2_1_i_i_reg_825");
    sc_trace(mVcdFile, q_chunk_V_ret2_2_i_i_reg_830, "q_chunk_V_ret2_2_i_i_reg_830");
    sc_trace(mVcdFile, q_chunk_V_ret2_3_i_i_reg_835, "q_chunk_V_ret2_3_i_i_reg_835");
    sc_trace(mVcdFile, q_chunk_V_ret2_4_i_i_reg_840, "q_chunk_V_ret2_4_i_i_reg_840");
    sc_trace(mVcdFile, q_chunk_V_ret2_5_i_i_reg_845, "q_chunk_V_ret2_5_i_i_reg_845");
    sc_trace(mVcdFile, q_chunk_V_ret2_6_i_i_reg_850, "q_chunk_V_ret2_6_i_i_reg_850");
    sc_trace(mVcdFile, r_V_ret3_6_i_i_reg_855, "r_V_ret3_6_i_i_reg_855");
    sc_trace(mVcdFile, p_Result_22_7_i_i_reg_860, "p_Result_22_7_i_i_reg_860");
    sc_trace(mVcdFile, p_Result_22_8_i_i_reg_865, "p_Result_22_8_i_i_reg_865");
    sc_trace(mVcdFile, p_Result_22_9_i_i_reg_870, "p_Result_22_9_i_i_reg_870");
    sc_trace(mVcdFile, p_Result_22_i_i_10_reg_875, "p_Result_22_i_i_10_reg_875");
    sc_trace(mVcdFile, p_Result_22_10_i_i_reg_880, "p_Result_22_10_i_i_reg_880");
    sc_trace(mVcdFile, p_Result_22_11_i_i_reg_885, "p_Result_22_11_i_i_reg_885");
    sc_trace(mVcdFile, p_Result_22_12_i_i_reg_890, "p_Result_22_12_i_i_reg_890");
    sc_trace(mVcdFile, p_Result_22_13_i_i_reg_895, "p_Result_22_13_i_i_reg_895");
    sc_trace(mVcdFile, p_Result_22_14_i_i_reg_900, "p_Result_22_14_i_i_reg_900");
    sc_trace(mVcdFile, p_Result_22_15_i_i_reg_905, "p_Result_22_15_i_i_reg_905");
    sc_trace(mVcdFile, tmp_9_fu_726_p1, "tmp_9_fu_726_p1");
    sc_trace(mVcdFile, tmp_9_reg_910, "tmp_9_reg_910");
    sc_trace(mVcdFile, tmp_10_fu_730_p1, "tmp_10_fu_730_p1");
    sc_trace(mVcdFile, tmp_10_reg_915, "tmp_10_reg_915");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_153_ap_ready, "grp_lut_div5_chunk_fu_153_ap_ready");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_153_d_V, "grp_lut_div5_chunk_fu_153_d_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_153_r_in_V, "grp_lut_div5_chunk_fu_153_r_in_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_153_ap_return_0, "grp_lut_div5_chunk_fu_153_ap_return_0");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_153_ap_return_1, "grp_lut_div5_chunk_fu_153_ap_return_1");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_160_ap_ready, "grp_lut_div5_chunk_fu_160_ap_ready");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_160_d_V, "grp_lut_div5_chunk_fu_160_d_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_160_ap_return_0, "grp_lut_div5_chunk_fu_160_ap_return_0");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_160_ap_return_1, "grp_lut_div5_chunk_fu_160_ap_return_1");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_166_ap_ready, "grp_lut_div5_chunk_fu_166_ap_ready");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_166_d_V, "grp_lut_div5_chunk_fu_166_d_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_166_ap_return_0, "grp_lut_div5_chunk_fu_166_ap_return_0");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_166_ap_return_1, "grp_lut_div5_chunk_fu_166_ap_return_1");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_172_ap_ready, "grp_lut_div5_chunk_fu_172_ap_ready");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_172_d_V, "grp_lut_div5_chunk_fu_172_d_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_172_ap_return_0, "grp_lut_div5_chunk_fu_172_ap_return_0");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_172_ap_return_1, "grp_lut_div5_chunk_fu_172_ap_return_1");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_178_ap_ready, "grp_lut_div5_chunk_fu_178_ap_ready");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_178_d_V, "grp_lut_div5_chunk_fu_178_d_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_178_ap_return_0, "grp_lut_div5_chunk_fu_178_ap_return_0");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_178_ap_return_1, "grp_lut_div5_chunk_fu_178_ap_return_1");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_184_ap_ready, "grp_lut_div5_chunk_fu_184_ap_ready");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_184_d_V, "grp_lut_div5_chunk_fu_184_d_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_184_ap_return_0, "grp_lut_div5_chunk_fu_184_ap_return_0");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_184_ap_return_1, "grp_lut_div5_chunk_fu_184_ap_return_1");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_190_ap_ready, "grp_lut_div5_chunk_fu_190_ap_ready");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_190_d_V, "grp_lut_div5_chunk_fu_190_d_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_190_ap_return_0, "grp_lut_div5_chunk_fu_190_ap_return_0");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_190_ap_return_1, "grp_lut_div5_chunk_fu_190_ap_return_1");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_196_ap_ready, "grp_lut_div5_chunk_fu_196_ap_ready");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_196_d_V, "grp_lut_div5_chunk_fu_196_d_V");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_196_ap_return_0, "grp_lut_div5_chunk_fu_196_ap_return_0");
    sc_trace(mVcdFile, grp_lut_div5_chunk_fu_196_ap_return_1, "grp_lut_div5_chunk_fu_196_ap_return_1");
    sc_trace(mVcdFile, call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_ready, "call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_ready");
    sc_trace(mVcdFile, call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_0, "call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_0");
    sc_trace(mVcdFile, call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_1, "call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_1");
    sc_trace(mVcdFile, call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_ready, "call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_ready");
    sc_trace(mVcdFile, call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_0, "call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_0");
    sc_trace(mVcdFile, call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_1, "call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_1");
    sc_trace(mVcdFile, call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_ready, "call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_ready");
    sc_trace(mVcdFile, call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_return_0, "call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_return_0");
    sc_trace(mVcdFile, call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_return_1, "call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_return_1");
    sc_trace(mVcdFile, new_mant_V_1_fu_760_p19, "new_mant_V_1_fu_760_p19");
    sc_trace(mVcdFile, ap_phi_mux_p_Repl2_s_phi_fu_147_p4, "ap_phi_mux_p_Repl2_s_phi_fu_147_p4");
    sc_trace(mVcdFile, p_Repl2_s_reg_144, "p_Repl2_s_reg_144");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, d_chunk_V_fu_544_p1, "d_chunk_V_fu_544_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_288_p1, "p_Val2_s_fu_288_p1");
    sc_trace(mVcdFile, tmp_fu_318_p4, "tmp_fu_318_p4");
    sc_trace(mVcdFile, icmp_fu_328_p2, "icmp_fu_328_p2");
    sc_trace(mVcdFile, new_exp_V_fu_300_p4, "new_exp_V_fu_300_p4");
    sc_trace(mVcdFile, shift_V_cast_cast_fu_334_p3, "shift_V_cast_cast_fu_334_p3");
    sc_trace(mVcdFile, tmp_2_fu_348_p2, "tmp_2_fu_348_p2");
    sc_trace(mVcdFile, tmp_7_fu_368_p2, "tmp_7_fu_368_p2");
    sc_trace(mVcdFile, p_new_exp_V_1_fu_360_p3, "p_new_exp_V_1_fu_360_p3");
    sc_trace(mVcdFile, new_exp_V_1_fu_354_p2, "new_exp_V_1_fu_354_p2");
    sc_trace(mVcdFile, tmp_8_fu_394_p4, "tmp_8_fu_394_p4");
    sc_trace(mVcdFile, tmp_4_fu_382_p2, "tmp_4_fu_382_p2");
    sc_trace(mVcdFile, tmp_5_fu_388_p2, "tmp_5_fu_388_p2");
    sc_trace(mVcdFile, sel_tmp3_demorgan_fu_422_p2, "sel_tmp3_demorgan_fu_422_p2");
    sc_trace(mVcdFile, icmp4_fu_404_p2, "icmp4_fu_404_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_428_p2, "sel_tmp3_fu_428_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_434_p2, "sel_tmp4_fu_434_p2");
    sc_trace(mVcdFile, shift_V_fu_410_p2, "shift_V_fu_410_p2");
    sc_trace(mVcdFile, shift_V_1_fu_416_p2, "shift_V_1_fu_416_p2");
    sc_trace(mVcdFile, shift_V_2_fu_440_p3, "shift_V_2_fu_440_p3");
    sc_trace(mVcdFile, sel_tmp7_fu_456_p2, "sel_tmp7_fu_456_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_462_p2, "sel_tmp8_fu_462_p2");
    sc_trace(mVcdFile, shift_V_3_fu_448_p3, "shift_V_3_fu_448_p3");
    sc_trace(mVcdFile, xf_V_5_cast_fu_314_p1, "xf_V_5_cast_fu_314_p1");
    sc_trace(mVcdFile, tmp_3_fu_476_p3, "tmp_3_fu_476_p3");
    sc_trace(mVcdFile, xf_V_1_fu_484_p3, "xf_V_1_fu_484_p3");
    sc_trace(mVcdFile, shift_V_4_fu_468_p3, "shift_V_4_fu_468_p3");
    sc_trace(mVcdFile, tmp_cast_fu_500_p1, "tmp_cast_fu_500_p1");
    sc_trace(mVcdFile, r_V_3_fu_504_p2, "r_V_3_fu_504_p2");
    sc_trace(mVcdFile, p_cast_fu_492_p1, "p_cast_fu_492_p1");
    sc_trace(mVcdFile, tmp_s_fu_496_p1, "tmp_s_fu_496_p1");
    sc_trace(mVcdFile, r_V_1_cast_fu_510_p1, "r_V_1_cast_fu_510_p1");
    sc_trace(mVcdFile, r_V_4_fu_514_p2, "r_V_4_fu_514_p2");
    sc_trace(mVcdFile, xf_V_3_fu_520_p3, "xf_V_3_fu_520_p3");
    sc_trace(mVcdFile, xf_V_fu_528_p2, "xf_V_fu_528_p2");
    sc_trace(mVcdFile, p_Result_i_i_fu_534_p4, "p_Result_i_i_fu_534_p4");
    sc_trace(mVcdFile, p_Result_s_fu_794_p4, "p_Result_s_fu_794_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("operator_double_div5.hdltvin.dat");
    mHdltvoutHandle.open("operator_double_div5.hdltvout.dat");
}

operator_double_div5::~operator_double_div5() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_lut_div5_chunk_fu_153;
    delete grp_lut_div5_chunk_fu_160;
    delete grp_lut_div5_chunk_fu_166;
    delete grp_lut_div5_chunk_fu_172;
    delete grp_lut_div5_chunk_fu_178;
    delete grp_lut_div5_chunk_fu_184;
    delete grp_lut_div5_chunk_fu_190;
    delete grp_lut_div5_chunk_fu_196;
    delete call_ret4_14_i_i_lut_div5_chunk_fu_202;
    delete call_ret4_15_i_i_lut_div5_chunk_fu_208;
    delete call_ret4_16_i_i_lut_div5_chunk_fu_214;
}

void operator_double_div5::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_1))) {
        p_Repl2_s_reg_144 = new_mant_V_fu_310_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        p_Repl2_s_reg_144 = new_mant_V_1_fu_760_p19.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        p_Repl2_1_reg_820 = p_Repl2_1_fu_374_p3.read();
        p_Repl2_2_reg_806 = p_Val2_s_fu_288_p1.read().range(63, 63);
        tmp_1_reg_816 = tmp_1_fu_342_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        p_Result_22_10_i_i_reg_880 = xf_V_fu_528_p2.read().range(20, 18);
        p_Result_22_11_i_i_reg_885 = xf_V_fu_528_p2.read().range(17, 15);
        p_Result_22_12_i_i_reg_890 = xf_V_fu_528_p2.read().range(14, 12);
        p_Result_22_13_i_i_reg_895 = xf_V_fu_528_p2.read().range(11, 9);
        p_Result_22_14_i_i_reg_900 = xf_V_fu_528_p2.read().range(8, 6);
        p_Result_22_15_i_i_reg_905 = xf_V_fu_528_p2.read().range(5, 3);
        p_Result_22_7_i_i_reg_860 = xf_V_fu_528_p2.read().range(32, 30);
        p_Result_22_8_i_i_reg_865 = xf_V_fu_528_p2.read().range(29, 27);
        p_Result_22_9_i_i_reg_870 = xf_V_fu_528_p2.read().range(26, 24);
        p_Result_22_i_i_10_reg_875 = xf_V_fu_528_p2.read().range(23, 21);
        q_chunk_V_ret2_1_i_i_reg_825 = grp_lut_div5_chunk_fu_166_ap_return_0.read();
        q_chunk_V_ret2_2_i_i_reg_830 = grp_lut_div5_chunk_fu_172_ap_return_0.read();
        q_chunk_V_ret2_3_i_i_reg_835 = grp_lut_div5_chunk_fu_178_ap_return_0.read();
        q_chunk_V_ret2_4_i_i_reg_840 = grp_lut_div5_chunk_fu_184_ap_return_0.read();
        q_chunk_V_ret2_5_i_i_reg_845 = grp_lut_div5_chunk_fu_190_ap_return_0.read();
        q_chunk_V_ret2_6_i_i_reg_850 = grp_lut_div5_chunk_fu_196_ap_return_0.read();
        r_V_ret3_6_i_i_reg_855 = grp_lut_div5_chunk_fu_196_ap_return_1.read();
        tmp_10_reg_915 = tmp_10_fu_730_p1.read();
        tmp_9_reg_910 = tmp_9_fu_726_p1.read();
    }
}

void operator_double_div5::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void operator_double_div5::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void operator_double_div5::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void operator_double_div5::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void operator_double_div5::thread_ap_phi_mux_p_Repl2_s_phi_fu_147_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        ap_phi_mux_p_Repl2_s_phi_fu_147_p4 = new_mant_V_1_fu_760_p19.read();
    } else {
        ap_phi_mux_p_Repl2_s_phi_fu_147_p4 = p_Repl2_s_reg_144.read();
    }
}

void operator_double_div5::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void operator_double_div5::thread_ap_return() {
    ap_return = p_Result_s_fu_794_p4.read();
}

void operator_double_div5::thread_d_chunk_V_fu_544_p1() {
    d_chunk_V_fu_544_p1 = esl_zext<3,2>(p_Result_i_i_fu_534_p4.read());
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_153_d_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_153_d_V = p_Result_22_7_i_i_reg_860.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_153_d_V = d_chunk_V_fu_544_p1.read();
    } else {
        grp_lut_div5_chunk_fu_153_d_V = "XXX";
    }
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_153_r_in_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_153_r_in_V = r_V_ret3_6_i_i_reg_855.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_153_r_in_V = ap_const_lv3_0;
    } else {
        grp_lut_div5_chunk_fu_153_r_in_V = "XXX";
    }
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_160_d_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_160_d_V = p_Result_22_8_i_i_reg_865.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_160_d_V = xf_V_fu_528_p2.read().range(53, 51);
    } else {
        grp_lut_div5_chunk_fu_160_d_V = "XXX";
    }
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_166_d_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_166_d_V = p_Result_22_9_i_i_reg_870.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_166_d_V = xf_V_fu_528_p2.read().range(50, 48);
    } else {
        grp_lut_div5_chunk_fu_166_d_V = "XXX";
    }
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_172_d_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_172_d_V = p_Result_22_i_i_10_reg_875.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_172_d_V = xf_V_fu_528_p2.read().range(47, 45);
    } else {
        grp_lut_div5_chunk_fu_172_d_V = "XXX";
    }
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_178_d_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_178_d_V = p_Result_22_10_i_i_reg_880.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_178_d_V = xf_V_fu_528_p2.read().range(44, 42);
    } else {
        grp_lut_div5_chunk_fu_178_d_V = "XXX";
    }
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_184_d_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_184_d_V = p_Result_22_11_i_i_reg_885.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_184_d_V = xf_V_fu_528_p2.read().range(41, 39);
    } else {
        grp_lut_div5_chunk_fu_184_d_V = "XXX";
    }
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_190_d_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_190_d_V = p_Result_22_12_i_i_reg_890.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_190_d_V = xf_V_fu_528_p2.read().range(38, 36);
    } else {
        grp_lut_div5_chunk_fu_190_d_V = "XXX";
    }
}

void operator_double_div5::thread_grp_lut_div5_chunk_fu_196_d_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_1_reg_816.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_196_d_V = p_Result_22_13_i_i_reg_895.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(tmp_1_fu_342_p2.read(), ap_const_lv1_0))) {
        grp_lut_div5_chunk_fu_196_d_V = xf_V_fu_528_p2.read().range(35, 33);
    } else {
        grp_lut_div5_chunk_fu_196_d_V = "XXX";
    }
}

void operator_double_div5::thread_icmp4_fu_404_p2() {
    icmp4_fu_404_p2 = (!tmp_8_fu_394_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_8_fu_394_p4.read() == ap_const_lv10_0);
}

void operator_double_div5::thread_icmp_fu_328_p2() {
    icmp_fu_328_p2 = (!tmp_fu_318_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_318_p4.read() == ap_const_lv2_0);
}

void operator_double_div5::thread_new_exp_V_1_fu_354_p2() {
    new_exp_V_1_fu_354_p2 = (!new_exp_V_fu_300_p4.read().is_01() || !shift_V_cast_cast_fu_334_p3.read().is_01())? sc_lv<11>(): (sc_biguint<11>(new_exp_V_fu_300_p4.read()) - sc_biguint<11>(shift_V_cast_cast_fu_334_p3.read()));
}

void operator_double_div5::thread_new_exp_V_fu_300_p4() {
    new_exp_V_fu_300_p4 = p_Val2_s_fu_288_p1.read().range(62, 52);
}

void operator_double_div5::thread_new_mant_V_1_fu_760_p19() {
    new_mant_V_1_fu_760_p19 = esl_concat<49,3>(esl_concat<46,3>(esl_concat<43,3>(esl_concat<40,3>(esl_concat<37,3>(esl_concat<34,3>(esl_concat<31,3>(esl_concat<28,3>(esl_concat<25,3>(esl_concat<22,3>(esl_concat<19,3>(esl_concat<16,3>(esl_concat<13,3>(esl_concat<10,3>(esl_concat<7,3>(esl_concat<4,3>(esl_concat<1,3>(tmp_10_reg_915.read(), q_chunk_V_ret2_1_i_i_reg_825.read()), q_chunk_V_ret2_2_i_i_reg_830.read()), q_chunk_V_ret2_3_i_i_reg_835.read()), q_chunk_V_ret2_4_i_i_reg_840.read()), q_chunk_V_ret2_5_i_i_reg_845.read()), q_chunk_V_ret2_6_i_i_reg_850.read()), grp_lut_div5_chunk_fu_153_ap_return_0.read()), grp_lut_div5_chunk_fu_160_ap_return_0.read()), grp_lut_div5_chunk_fu_166_ap_return_0.read()), grp_lut_div5_chunk_fu_172_ap_return_0.read()), grp_lut_div5_chunk_fu_178_ap_return_0.read()), grp_lut_div5_chunk_fu_184_ap_return_0.read()), grp_lut_div5_chunk_fu_190_ap_return_0.read()), grp_lut_div5_chunk_fu_196_ap_return_0.read()), call_ret4_14_i_i_lut_div5_chunk_fu_202_ap_return_0.read()), call_ret4_15_i_i_lut_div5_chunk_fu_208_ap_return_0.read()), call_ret4_16_i_i_lut_div5_chunk_fu_214_ap_return_0.read());
}

void operator_double_div5::thread_new_mant_V_fu_310_p1() {
    new_mant_V_fu_310_p1 = p_Val2_s_fu_288_p1.read().range(52-1, 0);
}

void operator_double_div5::thread_p_Repl2_1_fu_374_p3() {
    p_Repl2_1_fu_374_p3 = (!tmp_7_fu_368_p2.read()[0].is_01())? sc_lv<11>(): ((tmp_7_fu_368_p2.read()[0].to_bool())? p_new_exp_V_1_fu_360_p3.read(): new_exp_V_1_fu_354_p2.read());
}

void operator_double_div5::thread_p_Result_i_i_fu_534_p4() {
    p_Result_i_i_fu_534_p4 = xf_V_fu_528_p2.read().range(55, 54);
}

void operator_double_div5::thread_p_Result_s_fu_794_p4() {
    p_Result_s_fu_794_p4 = esl_concat<12,52>(esl_concat<1,11>(p_Repl2_2_reg_806.read(), p_Repl2_1_reg_820.read()), ap_phi_mux_p_Repl2_s_phi_fu_147_p4.read());
}

void operator_double_div5::thread_p_Val2_s_fu_288_p1() {
    p_Val2_s_fu_288_p1 = in_r.read();
}

void operator_double_div5::thread_p_cast_fu_492_p1() {
    p_cast_fu_492_p1 = esl_zext<56,53>(xf_V_1_fu_484_p3.read());
}

void operator_double_div5::thread_p_new_exp_V_1_fu_360_p3() {
    p_new_exp_V_1_fu_360_p3 = (!tmp_1_fu_342_p2.read()[0].is_01())? sc_lv<11>(): ((tmp_1_fu_342_p2.read()[0].to_bool())? ap_const_lv11_7FF: ap_const_lv11_0);
}

void operator_double_div5::thread_r_V_1_cast_fu_510_p1() {
    r_V_1_cast_fu_510_p1 = esl_zext<56,53>(r_V_3_fu_504_p2.read());
}

void operator_double_div5::thread_r_V_3_fu_504_p2() {
    r_V_3_fu_504_p2 = (!tmp_cast_fu_500_p1.read().is_01())? sc_lv<53>(): xf_V_1_fu_484_p3.read() >> (unsigned short)tmp_cast_fu_500_p1.read().to_uint();
}

void operator_double_div5::thread_r_V_4_fu_514_p2() {
    r_V_4_fu_514_p2 = (!tmp_s_fu_496_p1.read().is_01())? sc_lv<56>(): p_cast_fu_492_p1.read() << (unsigned short)tmp_s_fu_496_p1.read().to_uint();
}

void operator_double_div5::thread_sel_tmp3_demorgan_fu_422_p2() {
    sel_tmp3_demorgan_fu_422_p2 = (tmp_4_fu_382_p2.read() | tmp_5_fu_388_p2.read());
}

void operator_double_div5::thread_sel_tmp3_fu_428_p2() {
    sel_tmp3_fu_428_p2 = (sel_tmp3_demorgan_fu_422_p2.read() ^ ap_const_lv1_1);
}

void operator_double_div5::thread_sel_tmp4_fu_434_p2() {
    sel_tmp4_fu_434_p2 = (icmp4_fu_404_p2.read() & sel_tmp3_fu_428_p2.read());
}

void operator_double_div5::thread_sel_tmp7_fu_456_p2() {
    sel_tmp7_fu_456_p2 = (tmp_4_fu_382_p2.read() ^ ap_const_lv1_1);
}

void operator_double_div5::thread_sel_tmp8_fu_462_p2() {
    sel_tmp8_fu_462_p2 = (tmp_5_fu_388_p2.read() & sel_tmp7_fu_456_p2.read());
}

void operator_double_div5::thread_shift_V_1_fu_416_p2() {
    shift_V_1_fu_416_p2 = (!ap_const_lv11_7FF.is_01() || !new_exp_V_fu_300_p4.read().is_01())? sc_lv<11>(): (sc_bigint<11>(ap_const_lv11_7FF) + sc_biguint<11>(new_exp_V_fu_300_p4.read()));
}

void operator_double_div5::thread_shift_V_2_fu_440_p3() {
    shift_V_2_fu_440_p3 = (!sel_tmp4_fu_434_p2.read()[0].is_01())? sc_lv<11>(): ((sel_tmp4_fu_434_p2.read()[0].to_bool())? shift_V_fu_410_p2.read(): shift_V_1_fu_416_p2.read());
}

void operator_double_div5::thread_shift_V_3_fu_448_p3() {
    shift_V_3_fu_448_p3 = (!tmp_4_fu_382_p2.read()[0].is_01())? sc_lv<11>(): ((tmp_4_fu_382_p2.read()[0].to_bool())? ap_const_lv11_0: shift_V_2_fu_440_p3.read());
}

void operator_double_div5::thread_shift_V_4_fu_468_p3() {
    shift_V_4_fu_468_p3 = (!sel_tmp8_fu_462_p2.read()[0].is_01())? sc_lv<11>(): ((sel_tmp8_fu_462_p2.read()[0].to_bool())? shift_V_cast_cast_fu_334_p3.read(): shift_V_3_fu_448_p3.read());
}

void operator_double_div5::thread_shift_V_cast_cast_fu_334_p3() {
    shift_V_cast_cast_fu_334_p3 = (!icmp_fu_328_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_fu_328_p2.read()[0].to_bool())? ap_const_lv11_3: ap_const_lv11_2);
}

void operator_double_div5::thread_shift_V_fu_410_p2() {
    shift_V_fu_410_p2 = (!ap_const_lv11_1.is_01() || !new_exp_V_fu_300_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_1) - sc_biguint<11>(new_exp_V_fu_300_p4.read()));
}

void operator_double_div5::thread_tmp_10_fu_730_p1() {
    tmp_10_fu_730_p1 = grp_lut_div5_chunk_fu_160_ap_return_0.read().range(1-1, 0);
}

void operator_double_div5::thread_tmp_1_fu_342_p2() {
    tmp_1_fu_342_p2 = (!new_exp_V_fu_300_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(new_exp_V_fu_300_p4.read() == ap_const_lv11_7FF);
}

void operator_double_div5::thread_tmp_2_fu_348_p2() {
    tmp_2_fu_348_p2 = (!shift_V_cast_cast_fu_334_p3.read().is_01() || !new_exp_V_fu_300_p4.read().is_01())? sc_lv<1>(): (sc_biguint<11>(shift_V_cast_cast_fu_334_p3.read()) > sc_biguint<11>(new_exp_V_fu_300_p4.read()));
}

void operator_double_div5::thread_tmp_3_fu_476_p3() {
    tmp_3_fu_476_p3 = esl_concat<1,52>(ap_const_lv1_1, new_mant_V_fu_310_p1.read());
}

void operator_double_div5::thread_tmp_4_fu_382_p2() {
    tmp_4_fu_382_p2 = (!new_exp_V_fu_300_p4.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(new_exp_V_fu_300_p4.read() == ap_const_lv11_0);
}

void operator_double_div5::thread_tmp_5_fu_388_p2() {
    tmp_5_fu_388_p2 = (!shift_V_cast_cast_fu_334_p3.read().is_01() || !new_exp_V_fu_300_p4.read().is_01())? sc_lv<1>(): (sc_biguint<11>(shift_V_cast_cast_fu_334_p3.read()) < sc_biguint<11>(new_exp_V_fu_300_p4.read()));
}

void operator_double_div5::thread_tmp_7_fu_368_p2() {
    tmp_7_fu_368_p2 = (tmp_1_fu_342_p2.read() | tmp_2_fu_348_p2.read());
}

void operator_double_div5::thread_tmp_8_fu_394_p4() {
    tmp_8_fu_394_p4 = p_Val2_s_fu_288_p1.read().range(62, 53);
}

void operator_double_div5::thread_tmp_9_fu_726_p1() {
    tmp_9_fu_726_p1 = xf_V_fu_528_p2.read().range(3-1, 0);
}

void operator_double_div5::thread_tmp_cast_fu_500_p1() {
    tmp_cast_fu_500_p1 = esl_zext<53,11>(shift_V_4_fu_468_p3.read());
}

void operator_double_div5::thread_tmp_fu_318_p4() {
    tmp_fu_318_p4 = p_Val2_s_fu_288_p1.read().range(51, 50);
}

void operator_double_div5::thread_tmp_s_fu_496_p1() {
    tmp_s_fu_496_p1 = esl_zext<56,11>(shift_V_4_fu_468_p3.read());
}

void operator_double_div5::thread_xf_V_1_fu_484_p3() {
    xf_V_1_fu_484_p3 = (!tmp_4_fu_382_p2.read()[0].is_01())? sc_lv<53>(): ((tmp_4_fu_382_p2.read()[0].to_bool())? xf_V_5_cast_fu_314_p1.read(): tmp_3_fu_476_p3.read());
}

void operator_double_div5::thread_xf_V_3_fu_520_p3() {
    xf_V_3_fu_520_p3 = (!icmp4_fu_404_p2.read()[0].is_01())? sc_lv<56>(): ((icmp4_fu_404_p2.read()[0].to_bool())? r_V_1_cast_fu_510_p1.read(): r_V_4_fu_514_p2.read());
}

void operator_double_div5::thread_xf_V_5_cast_fu_314_p1() {
    xf_V_5_cast_fu_314_p1 = esl_zext<53,52>(new_mant_V_fu_310_p1.read());
}

void operator_double_div5::thread_xf_V_fu_528_p2() {
    xf_V_fu_528_p2 = (!ap_const_lv56_2.is_01() || !xf_V_3_fu_520_p3.read().is_01())? sc_lv<56>(): (sc_biguint<56>(ap_const_lv56_2) + sc_biguint<56>(xf_V_3_fu_520_p3.read()));
}

void operator_double_div5::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

void operator_double_div5::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r\" :  \"" << in_r.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

