// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _operator_int_div7_HH_
#define _operator_int_div7_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "lut_div7_chunk.h"

namespace ap_rtl {

struct operator_int_div7 : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > in_r;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    operator_int_div7(sc_module_name name);
    SC_HAS_PROCESS(operator_int_div7);

    ~operator_int_div7();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    lut_div7_chunk* grp_lut_div7_chunk_fu_68;
    lut_div7_chunk* grp_lut_div7_chunk_fu_75;
    lut_div7_chunk* grp_lut_div7_chunk_fu_81;
    lut_div7_chunk* grp_lut_div7_chunk_fu_87;
    lut_div7_chunk* grp_lut_div7_chunk_fu_93;
    lut_div7_chunk* call_ret4_9_i_i_lut_div7_chunk_fu_99;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<2> > tmp_fu_165_p1;
    sc_signal< sc_lv<2> > tmp_reg_292;
    sc_signal< sc_lv<3> > q_chunk_V_ret2_i_i_reg_297;
    sc_signal< sc_lv<3> > q_chunk_V_ret2_1_i_i_reg_302;
    sc_signal< sc_lv<3> > q_chunk_V_ret2_2_i_i_reg_307;
    sc_signal< sc_lv<3> > q_chunk_V_ret2_3_i_i_reg_312;
    sc_signal< sc_lv<3> > r_V_ret3_3_i_i_reg_317;
    sc_signal< sc_lv<3> > p_Result_19_4_i_i_reg_322;
    sc_signal< sc_lv<3> > p_Result_19_5_i_i_reg_327;
    sc_signal< sc_lv<3> > p_Result_19_6_i_i_reg_332;
    sc_signal< sc_lv<3> > p_Result_19_7_i_i_reg_337;
    sc_signal< sc_lv<3> > p_Result_19_8_i_i_reg_342;
    sc_signal< sc_lv<3> > tmp_1_fu_263_p1;
    sc_signal< sc_lv<3> > tmp_1_reg_347;
    sc_signal< sc_logic > grp_lut_div7_chunk_fu_68_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_68_d_V;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_68_r_in_V;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_68_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_68_ap_return_1;
    sc_signal< sc_logic > grp_lut_div7_chunk_fu_75_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_75_d_V;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_75_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_75_ap_return_1;
    sc_signal< sc_logic > grp_lut_div7_chunk_fu_81_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_81_d_V;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_81_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_81_ap_return_1;
    sc_signal< sc_logic > grp_lut_div7_chunk_fu_87_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_87_d_V;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_87_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_87_ap_return_1;
    sc_signal< sc_logic > grp_lut_div7_chunk_fu_93_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_93_d_V;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_93_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div7_chunk_fu_93_ap_return_1;
    sc_signal< sc_logic > call_ret4_9_i_i_lut_div7_chunk_fu_99_ap_ready;
    sc_signal< sc_lv<3> > call_ret4_9_i_i_lut_div7_chunk_fu_99_ap_return_0;
    sc_signal< sc_lv<3> > call_ret4_9_i_i_lut_div7_chunk_fu_99_ap_return_1;
    sc_signal< sc_lv<3> > d_chunk_V_fu_160_p1;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > p_Result_i_i_fu_150_p4;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_d_chunk_V_fu_160_p1();
    void thread_grp_lut_div7_chunk_fu_68_d_V();
    void thread_grp_lut_div7_chunk_fu_68_r_in_V();
    void thread_grp_lut_div7_chunk_fu_75_d_V();
    void thread_grp_lut_div7_chunk_fu_81_d_V();
    void thread_grp_lut_div7_chunk_fu_87_d_V();
    void thread_grp_lut_div7_chunk_fu_93_d_V();
    void thread_p_Result_i_i_fu_150_p4();
    void thread_tmp_1_fu_263_p1();
    void thread_tmp_fu_165_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
