// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="operator_float_div11,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160tfbg484-1,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.344000,HLS_SYN_LAT=50,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=623,HLS_SYN_LUT=852,HLS_VERSION=2018_2}" *)

module operator_float_div11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r,
        ap_return
);

parameter    ap_ST_fsm_state1 = 37'd1;
parameter    ap_ST_fsm_state2 = 37'd2;
parameter    ap_ST_fsm_state3 = 37'd4;
parameter    ap_ST_fsm_state4 = 37'd8;
parameter    ap_ST_fsm_state5 = 37'd16;
parameter    ap_ST_fsm_state6 = 37'd32;
parameter    ap_ST_fsm_state7 = 37'd64;
parameter    ap_ST_fsm_state8 = 37'd128;
parameter    ap_ST_fsm_state9 = 37'd256;
parameter    ap_ST_fsm_state10 = 37'd512;
parameter    ap_ST_fsm_state11 = 37'd1024;
parameter    ap_ST_fsm_state12 = 37'd2048;
parameter    ap_ST_fsm_state13 = 37'd4096;
parameter    ap_ST_fsm_state14 = 37'd8192;
parameter    ap_ST_fsm_state15 = 37'd16384;
parameter    ap_ST_fsm_state16 = 37'd32768;
parameter    ap_ST_fsm_state17 = 37'd65536;
parameter    ap_ST_fsm_state18 = 37'd131072;
parameter    ap_ST_fsm_state19 = 37'd262144;
parameter    ap_ST_fsm_state20 = 37'd524288;
parameter    ap_ST_fsm_state21 = 37'd1048576;
parameter    ap_ST_fsm_state22 = 37'd2097152;
parameter    ap_ST_fsm_state23 = 37'd4194304;
parameter    ap_ST_fsm_state24 = 37'd8388608;
parameter    ap_ST_fsm_state25 = 37'd16777216;
parameter    ap_ST_fsm_state26 = 37'd33554432;
parameter    ap_ST_fsm_state27 = 37'd67108864;
parameter    ap_ST_fsm_state28 = 37'd134217728;
parameter    ap_ST_fsm_state29 = 37'd268435456;
parameter    ap_ST_fsm_state30 = 37'd536870912;
parameter    ap_ST_fsm_state31 = 37'd1073741824;
parameter    ap_ST_fsm_state32 = 37'd2147483648;
parameter    ap_ST_fsm_state33 = 37'd4294967296;
parameter    ap_ST_fsm_state34 = 37'd8589934592;
parameter    ap_ST_fsm_state35 = 37'd17179869184;
parameter    ap_ST_fsm_state36 = 37'd34359738368;
parameter    ap_ST_fsm_state37 = 37'd68719476736;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_r;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [36:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] reg_145;
wire    ap_CS_fsm_state11;
wire    grp_lut_div11_chunk_fu_122_ap_idle;
wire    grp_lut_div11_chunk_fu_122_ap_ready;
wire    grp_lut_div11_chunk_fu_122_ap_done;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state35;
reg   [0:0] p_Repl2_2_reg_580;
reg   [7:0] new_exp_V_reg_585;
wire   [22:0] new_mant_V_1_fu_172_p1;
reg   [22:0] new_mant_V_1_reg_596;
wire   [0:0] tmp_fu_176_p2;
reg   [0:0] tmp_reg_603;
wire   [0:0] icmp_fu_192_p2;
reg   [0:0] icmp_reg_608;
wire   [7:0] shift_V_cast_cast_fu_198_p3;
reg   [7:0] shift_V_cast_cast_reg_614;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_3_fu_205_p2;
reg   [0:0] tmp_3_reg_621;
wire   [0:0] tmp_4_fu_210_p2;
reg   [0:0] tmp_4_reg_629;
wire   [7:0] shift_V_fu_215_p2;
reg   [7:0] shift_V_reg_635;
wire   [7:0] shift_V_1_fu_220_p2;
reg   [7:0] shift_V_1_reg_640;
wire   [7:0] shift_V_4_fu_271_p3;
reg   [7:0] shift_V_4_reg_645;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_5_fu_278_p2;
reg   [0:0] tmp_5_reg_651;
wire   [7:0] p_Repl2_1_fu_297_p3;
reg   [7:0] p_Repl2_1_reg_656;
wire    ap_CS_fsm_state4;
wire   [22:0] grp_fu_314_p2;
reg   [22:0] tmp_2_reg_676;
wire    ap_CS_fsm_state7;
wire   [27:0] tmp_13_fu_325_p1;
reg   [27:0] tmp_13_reg_681;
wire   [27:0] xf_V_fu_332_p3;
reg   [27:0] xf_V_reg_686;
wire    ap_CS_fsm_state8;
reg   [1:0] d_chunk_V_reg_692;
wire    ap_CS_fsm_state9;
reg   [1:0] d_chunk_V_1_reg_697;
reg   [1:0] d_chunk_V_2_reg_702;
reg   [1:0] d_chunk_V_3_reg_707;
reg   [1:0] d_chunk_V_4_reg_712;
reg   [1:0] d_chunk_V_5_reg_717;
reg   [1:0] d_chunk_V_6_reg_722;
reg   [1:0] d_chunk_V_7_reg_727;
reg   [1:0] d_chunk_V_8_reg_732;
reg   [1:0] d_chunk_V_9_reg_737;
reg   [1:0] d_chunk_V_10_reg_742;
reg   [1:0] d_chunk_V_11_reg_747;
reg   [1:0] d_chunk_V_12_reg_752;
wire   [1:0] d_chunk_V_13_fu_489_p1;
reg   [1:0] d_chunk_V_13_reg_757;
wire   [1:0] grp_lut_div11_chunk_fu_122_ap_return_0;
wire   [3:0] grp_lut_div11_chunk_fu_122_ap_return_1;
reg   [1:0] call_ret3_i_i_reg_762_0;
reg   [1:0] call_ret4_i_i_reg_767_0;
reg   [1:0] call_ret5_i_i_reg_772_0;
reg   [1:0] call_ret6_i_i_reg_777_0;
reg   [1:0] call_ret7_i_i_reg_782_0;
reg   [1:0] call_ret8_i_i_reg_787_0;
reg   [1:0] call_ret9_i_i_reg_792_0;
reg   [1:0] call_ret10_i_i_reg_797_0;
reg   [1:0] call_ret11_i_i_reg_802_0;
reg   [1:0] call_ret12_i_i_reg_807_0;
reg   [1:0] call_ret13_i_i_reg_812_0;
wire    grp_lut_div11_chunk_fu_122_ap_start;
reg   [1:0] grp_lut_div11_chunk_fu_122_d_V;
reg   [3:0] grp_lut_div11_chunk_fu_122_r_in_V;
reg    grp_lut_div11_chunk_fu_122_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state37;
wire   [31:0] p_Val2_s_fu_150_p1;
wire   [6:0] tmp_12_fu_182_p4;
wire   [0:0] sel_tmp2_demorgan_fu_233_p2;
wire   [0:0] sel_tmp2_fu_237_p2;
wire   [0:0] sel_tmp3_fu_243_p2;
wire   [7:0] shift_V_2_fu_248_p3;
wire   [0:0] sel_tmp6_fu_261_p2;
wire   [0:0] sel_tmp7_fu_266_p2;
wire   [7:0] shift_V_3_fu_254_p3;
wire   [0:0] tmp_1_fu_225_p2;
wire   [0:0] tmp_8_fu_291_p2;
wire   [7:0] p_s_fu_283_p3;
wire   [7:0] new_exp_V_1_fu_229_p2;
wire   [22:0] grp_fu_314_p1;
wire   [31:0] grp_fu_319_p0;
wire   [31:0] grp_fu_319_p1;
wire   [31:0] grp_fu_319_p2;
wire   [27:0] tmp_6_fu_329_p1;
reg   [27:0] p_Result_s_fu_338_p4;
wire   [27:0] xf_V_1_fu_347_p3;
wire   [27:0] xf_V_4_fu_353_p2;
wire   [0:0] tmp_16_fu_530_p1;
wire   [22:0] new_mant_V_fu_534_p13;
wire   [22:0] p_Repl2_s_fu_562_p3;
wire   [31:0] p_Result_1_fu_568_p4;
reg   [36:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 37'd1;
#0 grp_lut_div11_chunk_fu_122_ap_start_reg = 1'b0;
end

lut_div11_chunk grp_lut_div11_chunk_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lut_div11_chunk_fu_122_ap_start),
    .ap_done(grp_lut_div11_chunk_fu_122_ap_done),
    .ap_idle(grp_lut_div11_chunk_fu_122_ap_idle),
    .ap_ready(grp_lut_div11_chunk_fu_122_ap_ready),
    .d_V(grp_lut_div11_chunk_fu_122_d_V),
    .r_in_V(grp_lut_div11_chunk_fu_122_r_in_V),
    .ap_return_0(grp_lut_div11_chunk_fu_122_ap_return_0),
    .ap_return_1(grp_lut_div11_chunk_fu_122_ap_return_1)
);

operator_float_dibkb #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .OP( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 23 ))
operator_float_dibkb_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(new_mant_V_1_reg_596),
    .din1(grp_fu_314_p1),
    .ce(1'b1),
    .dout(grp_fu_314_p2)
);

operator_float_dicud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .OP( 0 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
operator_float_dicud_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_319_p0),
    .din1(grp_fu_319_p1),
    .ce(1'b1),
    .dout(grp_fu_319_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lut_div11_chunk_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10))) begin
            grp_lut_div11_chunk_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_lut_div11_chunk_fu_122_ap_ready == 1'b1)) begin
            grp_lut_div11_chunk_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        call_ret10_i_i_reg_797_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
        call_ret11_i_i_reg_802_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state33))) begin
        call_ret12_i_i_reg_807_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        call_ret13_i_i_reg_812_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        call_ret3_i_i_reg_762_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        call_ret4_i_i_reg_767_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        call_ret5_i_i_reg_772_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        call_ret6_i_i_reg_777_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        call_ret7_i_i_reg_782_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        call_ret8_i_i_reg_787_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        call_ret9_i_i_reg_792_0 <= grp_lut_div11_chunk_fu_122_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        d_chunk_V_10_reg_742 <= {{xf_V_4_fu_353_p2[7:6]}};
        d_chunk_V_11_reg_747 <= {{xf_V_4_fu_353_p2[5:4]}};
        d_chunk_V_12_reg_752 <= {{xf_V_4_fu_353_p2[3:2]}};
        d_chunk_V_13_reg_757 <= d_chunk_V_13_fu_489_p1;
        d_chunk_V_1_reg_697 <= {{xf_V_4_fu_353_p2[25:24]}};
        d_chunk_V_2_reg_702 <= {{xf_V_4_fu_353_p2[23:22]}};
        d_chunk_V_3_reg_707 <= {{xf_V_4_fu_353_p2[21:20]}};
        d_chunk_V_4_reg_712 <= {{xf_V_4_fu_353_p2[19:18]}};
        d_chunk_V_5_reg_717 <= {{xf_V_4_fu_353_p2[17:16]}};
        d_chunk_V_6_reg_722 <= {{xf_V_4_fu_353_p2[15:14]}};
        d_chunk_V_7_reg_727 <= {{xf_V_4_fu_353_p2[13:12]}};
        d_chunk_V_8_reg_732 <= {{xf_V_4_fu_353_p2[11:10]}};
        d_chunk_V_9_reg_737 <= {{xf_V_4_fu_353_p2[9:8]}};
        d_chunk_V_reg_692 <= {{xf_V_4_fu_353_p2[27:26]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_reg_608 <= icmp_fu_192_p2;
        new_exp_V_reg_585 <= {{p_Val2_s_fu_150_p1[30:23]}};
        new_mant_V_1_reg_596 <= new_mant_V_1_fu_172_p1;
        p_Repl2_2_reg_580 <= p_Val2_s_fu_150_p1[32'd31];
        tmp_reg_603 <= tmp_fu_176_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Repl2_1_reg_656 <= p_Repl2_1_fu_297_p3;
        shift_V_4_reg_645 <= shift_V_4_fu_271_p3;
        tmp_5_reg_651 <= tmp_5_fu_278_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state33)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state29)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21)) | ((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        reg_145 <= grp_lut_div11_chunk_fu_122_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        shift_V_1_reg_640 <= shift_V_1_fu_220_p2;
        shift_V_cast_cast_reg_614[2 : 0] <= shift_V_cast_cast_fu_198_p3[2 : 0];
        shift_V_reg_635 <= shift_V_fu_215_p2;
        tmp_3_reg_621 <= tmp_3_fu_205_p2;
        tmp_4_reg_629 <= tmp_4_fu_210_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_reg_608 == 1'd0))) begin
        tmp_13_reg_681 <= tmp_13_fu_325_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_reg_608 == 1'd1))) begin
        tmp_2_reg_676 <= grp_fu_314_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        xf_V_reg_686 <= xf_V_fu_332_p3;
    end
end

always @ (*) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_13_reg_757;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_12_reg_752;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_11_reg_747;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_10_reg_742;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_9_reg_737;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_8_reg_732;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_7_reg_727;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_6_reg_722;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_5_reg_717;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_4_reg_712;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_3_reg_707;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_2_reg_702;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_1_reg_697;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_lut_div11_chunk_fu_122_d_V = d_chunk_V_reg_692;
    end else begin
        grp_lut_div11_chunk_fu_122_d_V = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state21))) begin
        grp_lut_div11_chunk_fu_122_r_in_V = reg_145;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_lut_div11_chunk_fu_122_r_in_V = 4'd0;
    end else begin
        grp_lut_div11_chunk_fu_122_r_in_V = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((grp_lut_div11_chunk_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = p_Result_1_fu_568_p4;

assign d_chunk_V_13_fu_489_p1 = xf_V_4_fu_353_p2[1:0];

assign grp_fu_314_p1 = shift_V_4_reg_645;

assign grp_fu_319_p0 = new_mant_V_1_reg_596;

assign grp_fu_319_p1 = shift_V_4_reg_645;

assign grp_lut_div11_chunk_fu_122_ap_start = grp_lut_div11_chunk_fu_122_ap_start_reg;

assign icmp_fu_192_p2 = ((tmp_12_fu_182_p4 == 7'd0) ? 1'b1 : 1'b0);

assign new_exp_V_1_fu_229_p2 = (new_exp_V_reg_585 - shift_V_cast_cast_reg_614);

assign new_mant_V_1_fu_172_p1 = p_Val2_s_fu_150_p1[22:0];

assign new_mant_V_fu_534_p13 = {{{{{{{{{{{{tmp_16_fu_530_p1}, {call_ret4_i_i_reg_767_0}}, {call_ret5_i_i_reg_772_0}}, {call_ret6_i_i_reg_777_0}}, {call_ret7_i_i_reg_782_0}}, {call_ret8_i_i_reg_787_0}}, {call_ret9_i_i_reg_792_0}}, {call_ret10_i_i_reg_797_0}}, {call_ret11_i_i_reg_802_0}}, {call_ret12_i_i_reg_807_0}}, {call_ret13_i_i_reg_812_0}}, {grp_lut_div11_chunk_fu_122_ap_return_0}};

assign p_Repl2_1_fu_297_p3 = ((tmp_8_fu_291_p2[0:0] === 1'b1) ? p_s_fu_283_p3 : new_exp_V_1_fu_229_p2);

assign p_Repl2_s_fu_562_p3 = ((tmp_5_reg_651[0:0] === 1'b1) ? new_mant_V_1_reg_596 : new_mant_V_fu_534_p13);

assign p_Result_1_fu_568_p4 = {{{p_Repl2_2_reg_580}, {p_Repl2_1_reg_656}}, {p_Repl2_s_fu_562_p3}};

always @ (*) begin
    p_Result_s_fu_338_p4 = xf_V_reg_686;
    p_Result_s_fu_338_p4[32'd23] = |(1'd1);
end

assign p_Val2_s_fu_150_p1 = in_r;

assign p_s_fu_283_p3 = ((tmp_5_fu_278_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign sel_tmp2_demorgan_fu_233_p2 = (tmp_4_reg_629 | tmp_3_reg_621);

assign sel_tmp2_fu_237_p2 = (sel_tmp2_demorgan_fu_233_p2 ^ 1'd1);

assign sel_tmp3_fu_243_p2 = (sel_tmp2_fu_237_p2 & icmp_reg_608);

assign sel_tmp6_fu_261_p2 = (tmp_3_reg_621 ^ 1'd1);

assign sel_tmp7_fu_266_p2 = (tmp_4_reg_629 & sel_tmp6_fu_261_p2);

assign shift_V_1_fu_220_p2 = ($signed(8'd255) + $signed(new_exp_V_reg_585));

assign shift_V_2_fu_248_p3 = ((sel_tmp3_fu_243_p2[0:0] === 1'b1) ? shift_V_reg_635 : shift_V_1_reg_640);

assign shift_V_3_fu_254_p3 = ((tmp_3_reg_621[0:0] === 1'b1) ? 8'd0 : shift_V_2_fu_248_p3);

assign shift_V_4_fu_271_p3 = ((sel_tmp7_fu_266_p2[0:0] === 1'b1) ? shift_V_cast_cast_reg_614 : shift_V_3_fu_254_p3);

assign shift_V_cast_cast_fu_198_p3 = ((tmp_reg_603[0:0] === 1'b1) ? 8'd4 : 8'd3);

assign shift_V_fu_215_p2 = (8'd1 - new_exp_V_reg_585);

assign tmp_12_fu_182_p4 = {{p_Val2_s_fu_150_p1[30:24]}};

assign tmp_13_fu_325_p1 = grp_fu_319_p2[27:0];

assign tmp_16_fu_530_p1 = call_ret3_i_i_reg_762_0[0:0];

assign tmp_1_fu_225_p2 = ((shift_V_cast_cast_reg_614 > new_exp_V_reg_585) ? 1'b1 : 1'b0);

assign tmp_3_fu_205_p2 = ((new_exp_V_reg_585 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_4_fu_210_p2 = ((shift_V_cast_cast_fu_198_p3 < new_exp_V_reg_585) ? 1'b1 : 1'b0);

assign tmp_5_fu_278_p2 = ((new_exp_V_reg_585 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_6_fu_329_p1 = tmp_2_reg_676;

assign tmp_8_fu_291_p2 = (tmp_5_fu_278_p2 | tmp_1_fu_225_p2);

assign tmp_fu_176_p2 = ((new_mant_V_1_fu_172_p1 < 23'd3145728) ? 1'b1 : 1'b0);

assign xf_V_1_fu_347_p3 = ((tmp_3_reg_621[0:0] === 1'b1) ? xf_V_reg_686 : p_Result_s_fu_338_p4);

assign xf_V_4_fu_353_p2 = (28'd5 + xf_V_1_fu_347_p3);

assign xf_V_fu_332_p3 = ((icmp_reg_608[0:0] === 1'b1) ? tmp_6_fu_329_p1 : tmp_13_reg_681);

always @ (posedge ap_clk) begin
    shift_V_cast_cast_reg_614[7:3] <= 5'b00000;
end

endmodule //operator_float_div11
