// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _operator_long_div6_HH_
#define _operator_long_div6_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "lut_div3_chunk.h"

namespace ap_rtl {

struct operator_long_div6 : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<64> > in_r;
    sc_out< sc_lv<64> > ap_return;


    // Module declarations
    operator_long_div6(sc_module_name name);
    SC_HAS_PROCESS(operator_long_div6);

    ~operator_long_div6();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    lut_div3_chunk* grp_lut_div3_chunk_fu_98;
    lut_div3_chunk* grp_lut_div3_chunk_fu_105;
    lut_div3_chunk* grp_lut_div3_chunk_fu_111;
    lut_div3_chunk* grp_lut_div3_chunk_fu_117;
    lut_div3_chunk* grp_lut_div3_chunk_fu_123;
    lut_div3_chunk* grp_lut_div3_chunk_fu_129;
    lut_div3_chunk* grp_lut_div3_chunk_fu_135;
    lut_div3_chunk* grp_lut_div3_chunk_fu_141;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<3> > tmp_fu_229_p1;
    sc_signal< sc_lv<3> > tmp_reg_426;
    sc_signal< sc_lv<4> > q_chunk_V_ret2_i_i_reg_431;
    sc_signal< sc_lv<4> > q_chunk_V_ret2_1_i_i_reg_436;
    sc_signal< sc_lv<4> > q_chunk_V_ret2_2_i_i_reg_441;
    sc_signal< sc_lv<4> > q_chunk_V_ret2_3_i_i_reg_446;
    sc_signal< sc_lv<4> > q_chunk_V_ret2_4_i_i_reg_451;
    sc_signal< sc_lv<4> > q_chunk_V_ret2_5_i_i_reg_456;
    sc_signal< sc_lv<4> > q_chunk_V_ret2_6_i_i_reg_461;
    sc_signal< sc_lv<2> > r_V_ret3_6_i_i_reg_466;
    sc_signal< sc_lv<4> > p_Result_19_7_i_i_reg_471;
    sc_signal< sc_lv<4> > p_Result_19_8_i_i_reg_476;
    sc_signal< sc_lv<4> > p_Result_19_9_i_i_reg_481;
    sc_signal< sc_lv<4> > p_Result_19_i_i_4_reg_486;
    sc_signal< sc_lv<4> > p_Result_19_10_i_i_reg_491;
    sc_signal< sc_lv<4> > p_Result_19_11_i_i_reg_496;
    sc_signal< sc_lv<4> > p_Result_19_12_i_i_reg_501;
    sc_signal< sc_lv<4> > p_Result_19_13_i_i_reg_506;
    sc_signal< sc_logic > grp_lut_div3_chunk_fu_98_ap_ready;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_98_d_V;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_98_r_in_V;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_98_ap_return_0;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_98_ap_return_1;
    sc_signal< sc_logic > grp_lut_div3_chunk_fu_105_ap_ready;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_105_d_V;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_105_ap_return_0;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_105_ap_return_1;
    sc_signal< sc_logic > grp_lut_div3_chunk_fu_111_ap_ready;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_111_d_V;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_111_ap_return_0;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_111_ap_return_1;
    sc_signal< sc_logic > grp_lut_div3_chunk_fu_117_ap_ready;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_117_d_V;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_117_ap_return_0;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_117_ap_return_1;
    sc_signal< sc_logic > grp_lut_div3_chunk_fu_123_ap_ready;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_123_d_V;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_123_ap_return_0;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_123_ap_return_1;
    sc_signal< sc_logic > grp_lut_div3_chunk_fu_129_ap_ready;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_129_d_V;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_129_ap_return_0;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_129_ap_return_1;
    sc_signal< sc_logic > grp_lut_div3_chunk_fu_135_ap_ready;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_135_d_V;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_135_ap_return_0;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_135_ap_return_1;
    sc_signal< sc_logic > grp_lut_div3_chunk_fu_141_ap_ready;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_141_d_V;
    sc_signal< sc_lv<4> > grp_lut_div3_chunk_fu_141_ap_return_0;
    sc_signal< sc_lv<2> > grp_lut_div3_chunk_fu_141_ap_return_1;
    sc_signal< sc_lv<4> > d_chunk_V_fu_224_p1;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<3> > p_Result_i_i_fu_214_p4;
    sc_signal< sc_lv<63> > p_Result_16_i_i_fu_394_p17;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_3D;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_39;
    static const sc_lv<32> ap_const_lv32_3C;
    static const sc_lv<32> ap_const_lv32_35;
    static const sc_lv<32> ap_const_lv32_38;
    static const sc_lv<32> ap_const_lv32_31;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_2D;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_29;
    static const sc_lv<32> ap_const_lv32_2C;
    static const sc_lv<32> ap_const_lv32_25;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<32> ap_const_lv32_21;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_4;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_d_chunk_V_fu_224_p1();
    void thread_grp_lut_div3_chunk_fu_105_d_V();
    void thread_grp_lut_div3_chunk_fu_111_d_V();
    void thread_grp_lut_div3_chunk_fu_117_d_V();
    void thread_grp_lut_div3_chunk_fu_123_d_V();
    void thread_grp_lut_div3_chunk_fu_129_d_V();
    void thread_grp_lut_div3_chunk_fu_135_d_V();
    void thread_grp_lut_div3_chunk_fu_141_d_V();
    void thread_grp_lut_div3_chunk_fu_98_d_V();
    void thread_grp_lut_div3_chunk_fu_98_r_in_V();
    void thread_p_Result_16_i_i_fu_394_p17();
    void thread_p_Result_i_i_fu_214_p4();
    void thread_tmp_fu_229_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
