// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _operator_int_div10_HH_
#define _operator_int_div10_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "lut_div5_chunk.h"

namespace ap_rtl {

struct operator_int_div10 : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > in_r;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    operator_int_div10(sc_module_name name);
    SC_HAS_PROCESS(operator_int_div10);

    ~operator_int_div10();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    lut_div5_chunk* grp_lut_div5_chunk_fu_74;
    lut_div5_chunk* grp_lut_div5_chunk_fu_81;
    lut_div5_chunk* grp_lut_div5_chunk_fu_87;
    lut_div5_chunk* grp_lut_div5_chunk_fu_93;
    lut_div5_chunk* grp_lut_div5_chunk_fu_99;
    lut_div5_chunk* call_ret4_9_i_i_lut_div5_chunk_fu_105;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > tmp_1_fu_169_p1;
    sc_signal< sc_lv<1> > tmp_1_reg_306;
    sc_signal< sc_lv<3> > q_chunk_V_ret2_i_i_reg_311;
    sc_signal< sc_lv<3> > q_chunk_V_ret2_1_i_i_reg_316;
    sc_signal< sc_lv<3> > q_chunk_V_ret2_2_i_i_reg_321;
    sc_signal< sc_lv<3> > q_chunk_V_ret2_3_i_i_reg_326;
    sc_signal< sc_lv<3> > r_V_ret3_3_i_i_reg_331;
    sc_signal< sc_lv<3> > p_Result_19_4_i_i_reg_336;
    sc_signal< sc_lv<3> > p_Result_19_5_i_i_reg_341;
    sc_signal< sc_lv<3> > p_Result_19_6_i_i_reg_346;
    sc_signal< sc_lv<3> > p_Result_19_7_i_i_reg_351;
    sc_signal< sc_lv<3> > p_Result_19_8_i_i_reg_356;
    sc_signal< sc_lv<3> > p_Result_19_9_i_i_reg_361;
    sc_signal< sc_logic > grp_lut_div5_chunk_fu_74_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_74_d_V;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_74_r_in_V;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_74_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_74_ap_return_1;
    sc_signal< sc_logic > grp_lut_div5_chunk_fu_81_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_81_d_V;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_81_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_81_ap_return_1;
    sc_signal< sc_logic > grp_lut_div5_chunk_fu_87_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_87_d_V;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_87_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_87_ap_return_1;
    sc_signal< sc_logic > grp_lut_div5_chunk_fu_93_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_93_d_V;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_93_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_93_ap_return_1;
    sc_signal< sc_logic > grp_lut_div5_chunk_fu_99_ap_ready;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_99_d_V;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_99_ap_return_0;
    sc_signal< sc_lv<3> > grp_lut_div5_chunk_fu_99_ap_return_1;
    sc_signal< sc_logic > call_ret4_9_i_i_lut_div5_chunk_fu_105_ap_ready;
    sc_signal< sc_lv<3> > call_ret4_9_i_i_lut_div5_chunk_fu_105_ap_return_0;
    sc_signal< sc_lv<3> > call_ret4_9_i_i_lut_div5_chunk_fu_105_ap_return_1;
    sc_signal< sc_lv<3> > d_chunk_V_fu_164_p1;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_fu_156_p3;
    sc_signal< sc_lv<31> > p_Result_16_9_i_i_fu_281_p12;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_d_chunk_V_fu_164_p1();
    void thread_grp_lut_div5_chunk_fu_74_d_V();
    void thread_grp_lut_div5_chunk_fu_74_r_in_V();
    void thread_grp_lut_div5_chunk_fu_81_d_V();
    void thread_grp_lut_div5_chunk_fu_87_d_V();
    void thread_grp_lut_div5_chunk_fu_93_d_V();
    void thread_grp_lut_div5_chunk_fu_99_d_V();
    void thread_p_Result_16_9_i_i_fu_281_p12();
    void thread_tmp_1_fu_169_p1();
    void thread_tmp_fu_156_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
