// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="operator_double_div3,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160tfbg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=29.069000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=121,HLS_SYN_LUT=13939,HLS_VERSION=2018_2}" *)

module operator_double_div3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] in_r;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] p_Repl2_2_reg_663;
wire   [51:0] new_mant_V_fu_248_p1;
wire   [0:0] tmp_1_fu_272_p2;
reg   [0:0] tmp_1_reg_673;
wire   [10:0] p_Repl2_1_fu_304_p3;
reg   [10:0] p_Repl2_1_reg_677;
reg   [3:0] q_chunk_V_ret2_i_i_reg_682;
reg   [3:0] q_chunk_V_ret2_1_i_i_reg_687;
reg   [3:0] q_chunk_V_ret2_2_i_i_reg_692;
reg   [3:0] q_chunk_V_ret2_3_i_i_reg_697;
reg   [3:0] q_chunk_V_ret2_4_i_i_reg_702;
reg   [1:0] r_V_ret3_4_i_i_reg_707;
reg   [3:0] p_Result_22_5_i_i_reg_712;
reg   [3:0] p_Result_22_6_i_i_reg_717;
reg   [3:0] p_Result_22_7_i_i_reg_722;
reg   [3:0] p_Result_22_8_i_i_reg_727;
reg   [3:0] p_Result_22_9_i_i_reg_732;
reg   [3:0] p_Result_22_i_i_8_reg_737;
reg   [3:0] p_Result_22_10_i_i_reg_742;
wire   [3:0] tmp_9_fu_604_p1;
reg   [3:0] tmp_9_reg_747;
wire    grp_lut_div3_chunk_fu_127_ap_ready;
reg   [3:0] grp_lut_div3_chunk_fu_127_d_V;
reg   [1:0] grp_lut_div3_chunk_fu_127_r_in_V;
wire   [3:0] grp_lut_div3_chunk_fu_127_ap_return_0;
wire   [1:0] grp_lut_div3_chunk_fu_127_ap_return_1;
wire    grp_lut_div3_chunk_fu_134_ap_ready;
reg   [3:0] grp_lut_div3_chunk_fu_134_d_V;
wire   [3:0] grp_lut_div3_chunk_fu_134_ap_return_0;
wire   [1:0] grp_lut_div3_chunk_fu_134_ap_return_1;
wire    grp_lut_div3_chunk_fu_140_ap_ready;
reg   [3:0] grp_lut_div3_chunk_fu_140_d_V;
wire   [3:0] grp_lut_div3_chunk_fu_140_ap_return_0;
wire   [1:0] grp_lut_div3_chunk_fu_140_ap_return_1;
wire    grp_lut_div3_chunk_fu_146_ap_ready;
reg   [3:0] grp_lut_div3_chunk_fu_146_d_V;
wire   [3:0] grp_lut_div3_chunk_fu_146_ap_return_0;
wire   [1:0] grp_lut_div3_chunk_fu_146_ap_return_1;
wire    grp_lut_div3_chunk_fu_152_ap_ready;
reg   [3:0] grp_lut_div3_chunk_fu_152_d_V;
wire   [3:0] grp_lut_div3_chunk_fu_152_ap_return_0;
wire   [1:0] grp_lut_div3_chunk_fu_152_ap_return_1;
wire    grp_lut_div3_chunk_fu_158_ap_ready;
reg   [3:0] grp_lut_div3_chunk_fu_158_d_V;
wire   [3:0] grp_lut_div3_chunk_fu_158_ap_return_0;
wire   [1:0] grp_lut_div3_chunk_fu_158_ap_return_1;
wire    call_ret4_10_i_i_lut_div3_chunk_fu_164_ap_ready;
wire   [3:0] call_ret4_10_i_i_lut_div3_chunk_fu_164_ap_return_0;
wire   [1:0] call_ret4_10_i_i_lut_div3_chunk_fu_164_ap_return_1;
wire    call_ret4_11_i_i_lut_div3_chunk_fu_170_ap_ready;
wire   [3:0] call_ret4_11_i_i_lut_div3_chunk_fu_170_ap_return_0;
wire   [1:0] call_ret4_11_i_i_lut_div3_chunk_fu_170_ap_return_1;
wire   [51:0] new_mant_V_1_fu_625_p14;
reg   [51:0] ap_phi_mux_p_Repl2_s_phi_fu_121_p4;
reg   [51:0] p_Repl2_s_reg_118;
wire    ap_CS_fsm_state2;
wire   [3:0] d_chunk_V_fu_474_p1;
wire   [63:0] p_Val2_s_fu_226_p1;
wire   [0:0] tmp_fu_256_p3;
wire   [10:0] new_exp_V_fu_238_p4;
wire   [10:0] shift_V_cast_cast_fu_264_p3;
wire   [0:0] tmp_2_fu_278_p2;
wire   [0:0] tmp_7_fu_298_p2;
wire   [10:0] p_new_exp_V_1_fu_290_p3;
wire   [10:0] new_exp_V_1_fu_284_p2;
wire   [9:0] tmp_8_fu_324_p4;
wire   [0:0] tmp_4_fu_312_p2;
wire   [0:0] tmp_5_fu_318_p2;
wire   [0:0] sel_tmp3_demorgan_fu_352_p2;
wire   [0:0] icmp_fu_334_p2;
wire   [0:0] sel_tmp3_fu_358_p2;
wire   [0:0] sel_tmp4_fu_364_p2;
wire   [10:0] shift_V_fu_340_p2;
wire   [10:0] shift_V_1_fu_346_p2;
wire   [10:0] shift_V_2_fu_370_p3;
wire   [0:0] sel_tmp7_fu_386_p2;
wire   [0:0] sel_tmp8_fu_392_p2;
wire   [10:0] shift_V_3_fu_378_p3;
wire   [52:0] xf_V_5_cast_fu_252_p1;
wire   [52:0] tmp_3_fu_406_p3;
wire   [52:0] xf_V_1_fu_414_p3;
wire   [10:0] shift_V_4_fu_398_p3;
wire   [52:0] tmp_cast_fu_430_p1;
wire   [52:0] r_V_3_fu_434_p2;
wire   [54:0] p_cast_fu_422_p1;
wire   [54:0] tmp_s_fu_426_p1;
wire   [54:0] r_V_1_cast_fu_440_p1;
wire   [54:0] r_V_4_fu_444_p2;
wire   [54:0] xf_V_3_fu_450_p3;
wire   [54:0] xf_V_fu_458_p2;
wire   [2:0] p_Result_i_i_fu_464_p4;
wire   [63:0] p_Result_s_fu_651_p4;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

lut_div3_chunk grp_lut_div3_chunk_fu_127(
    .ap_ready(grp_lut_div3_chunk_fu_127_ap_ready),
    .d_V(grp_lut_div3_chunk_fu_127_d_V),
    .r_in_V(grp_lut_div3_chunk_fu_127_r_in_V),
    .ap_return_0(grp_lut_div3_chunk_fu_127_ap_return_0),
    .ap_return_1(grp_lut_div3_chunk_fu_127_ap_return_1)
);

lut_div3_chunk grp_lut_div3_chunk_fu_134(
    .ap_ready(grp_lut_div3_chunk_fu_134_ap_ready),
    .d_V(grp_lut_div3_chunk_fu_134_d_V),
    .r_in_V(grp_lut_div3_chunk_fu_127_ap_return_1),
    .ap_return_0(grp_lut_div3_chunk_fu_134_ap_return_0),
    .ap_return_1(grp_lut_div3_chunk_fu_134_ap_return_1)
);

lut_div3_chunk grp_lut_div3_chunk_fu_140(
    .ap_ready(grp_lut_div3_chunk_fu_140_ap_ready),
    .d_V(grp_lut_div3_chunk_fu_140_d_V),
    .r_in_V(grp_lut_div3_chunk_fu_134_ap_return_1),
    .ap_return_0(grp_lut_div3_chunk_fu_140_ap_return_0),
    .ap_return_1(grp_lut_div3_chunk_fu_140_ap_return_1)
);

lut_div3_chunk grp_lut_div3_chunk_fu_146(
    .ap_ready(grp_lut_div3_chunk_fu_146_ap_ready),
    .d_V(grp_lut_div3_chunk_fu_146_d_V),
    .r_in_V(grp_lut_div3_chunk_fu_140_ap_return_1),
    .ap_return_0(grp_lut_div3_chunk_fu_146_ap_return_0),
    .ap_return_1(grp_lut_div3_chunk_fu_146_ap_return_1)
);

lut_div3_chunk grp_lut_div3_chunk_fu_152(
    .ap_ready(grp_lut_div3_chunk_fu_152_ap_ready),
    .d_V(grp_lut_div3_chunk_fu_152_d_V),
    .r_in_V(grp_lut_div3_chunk_fu_146_ap_return_1),
    .ap_return_0(grp_lut_div3_chunk_fu_152_ap_return_0),
    .ap_return_1(grp_lut_div3_chunk_fu_152_ap_return_1)
);

lut_div3_chunk grp_lut_div3_chunk_fu_158(
    .ap_ready(grp_lut_div3_chunk_fu_158_ap_ready),
    .d_V(grp_lut_div3_chunk_fu_158_d_V),
    .r_in_V(grp_lut_div3_chunk_fu_152_ap_return_1),
    .ap_return_0(grp_lut_div3_chunk_fu_158_ap_return_0),
    .ap_return_1(grp_lut_div3_chunk_fu_158_ap_return_1)
);

lut_div3_chunk call_ret4_10_i_i_lut_div3_chunk_fu_164(
    .ap_ready(call_ret4_10_i_i_lut_div3_chunk_fu_164_ap_ready),
    .d_V(p_Result_22_10_i_i_reg_742),
    .r_in_V(grp_lut_div3_chunk_fu_158_ap_return_1),
    .ap_return_0(call_ret4_10_i_i_lut_div3_chunk_fu_164_ap_return_0),
    .ap_return_1(call_ret4_10_i_i_lut_div3_chunk_fu_164_ap_return_1)
);

lut_div3_chunk call_ret4_11_i_i_lut_div3_chunk_fu_170(
    .ap_ready(call_ret4_11_i_i_lut_div3_chunk_fu_170_ap_ready),
    .d_V(tmp_9_reg_747),
    .r_in_V(call_ret4_10_i_i_lut_div3_chunk_fu_164_ap_return_1),
    .ap_return_0(call_ret4_11_i_i_lut_div3_chunk_fu_170_ap_return_0),
    .ap_return_1(call_ret4_11_i_i_lut_div3_chunk_fu_170_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (tmp_1_fu_272_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Repl2_s_reg_118 <= new_mant_V_fu_248_p1;
    end else if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_Repl2_s_reg_118 <= new_mant_V_1_fu_625_p14;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Repl2_1_reg_677 <= p_Repl2_1_fu_304_p3;
        p_Repl2_2_reg_663 <= p_Val2_s_fu_226_p1[32'd63];
        tmp_1_reg_673 <= tmp_1_fu_272_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (tmp_1_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Result_22_10_i_i_reg_742 <= {{xf_V_fu_458_p2[7:4]}};
        p_Result_22_5_i_i_reg_712 <= {{xf_V_fu_458_p2[31:28]}};
        p_Result_22_6_i_i_reg_717 <= {{xf_V_fu_458_p2[27:24]}};
        p_Result_22_7_i_i_reg_722 <= {{xf_V_fu_458_p2[23:20]}};
        p_Result_22_8_i_i_reg_727 <= {{xf_V_fu_458_p2[19:16]}};
        p_Result_22_9_i_i_reg_732 <= {{xf_V_fu_458_p2[15:12]}};
        p_Result_22_i_i_8_reg_737 <= {{xf_V_fu_458_p2[11:8]}};
        q_chunk_V_ret2_1_i_i_reg_687 <= grp_lut_div3_chunk_fu_140_ap_return_0;
        q_chunk_V_ret2_2_i_i_reg_692 <= grp_lut_div3_chunk_fu_146_ap_return_0;
        q_chunk_V_ret2_3_i_i_reg_697 <= grp_lut_div3_chunk_fu_152_ap_return_0;
        q_chunk_V_ret2_4_i_i_reg_702 <= grp_lut_div3_chunk_fu_158_ap_return_0;
        q_chunk_V_ret2_i_i_reg_682 <= grp_lut_div3_chunk_fu_134_ap_return_0;
        r_V_ret3_4_i_i_reg_707 <= grp_lut_div3_chunk_fu_158_ap_return_1;
        tmp_9_reg_747 <= tmp_9_fu_604_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_phi_mux_p_Repl2_s_phi_fu_121_p4 = new_mant_V_1_fu_625_p14;
    end else begin
        ap_phi_mux_p_Repl2_s_phi_fu_121_p4 = p_Repl2_s_reg_118;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_lut_div3_chunk_fu_127_d_V = p_Result_22_5_i_i_reg_712;
    end else if (((tmp_1_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_lut_div3_chunk_fu_127_d_V = d_chunk_V_fu_474_p1;
    end else begin
        grp_lut_div3_chunk_fu_127_d_V = 'bx;
    end
end

always @ (*) begin
    if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_lut_div3_chunk_fu_127_r_in_V = r_V_ret3_4_i_i_reg_707;
    end else if (((tmp_1_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_lut_div3_chunk_fu_127_r_in_V = 2'd0;
    end else begin
        grp_lut_div3_chunk_fu_127_r_in_V = 'bx;
    end
end

always @ (*) begin
    if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_lut_div3_chunk_fu_134_d_V = p_Result_22_6_i_i_reg_717;
    end else if (((tmp_1_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_lut_div3_chunk_fu_134_d_V = {{xf_V_fu_458_p2[51:48]}};
    end else begin
        grp_lut_div3_chunk_fu_134_d_V = 'bx;
    end
end

always @ (*) begin
    if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_lut_div3_chunk_fu_140_d_V = p_Result_22_7_i_i_reg_722;
    end else if (((tmp_1_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_lut_div3_chunk_fu_140_d_V = {{xf_V_fu_458_p2[47:44]}};
    end else begin
        grp_lut_div3_chunk_fu_140_d_V = 'bx;
    end
end

always @ (*) begin
    if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_lut_div3_chunk_fu_146_d_V = p_Result_22_8_i_i_reg_727;
    end else if (((tmp_1_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_lut_div3_chunk_fu_146_d_V = {{xf_V_fu_458_p2[43:40]}};
    end else begin
        grp_lut_div3_chunk_fu_146_d_V = 'bx;
    end
end

always @ (*) begin
    if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_lut_div3_chunk_fu_152_d_V = p_Result_22_9_i_i_reg_732;
    end else if (((tmp_1_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_lut_div3_chunk_fu_152_d_V = {{xf_V_fu_458_p2[39:36]}};
    end else begin
        grp_lut_div3_chunk_fu_152_d_V = 'bx;
    end
end

always @ (*) begin
    if (((tmp_1_reg_673 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_lut_div3_chunk_fu_158_d_V = p_Result_22_i_i_8_reg_737;
    end else if (((tmp_1_fu_272_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_lut_div3_chunk_fu_158_d_V = {{xf_V_fu_458_p2[35:32]}};
    end else begin
        grp_lut_div3_chunk_fu_158_d_V = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return = p_Result_s_fu_651_p4;

assign d_chunk_V_fu_474_p1 = p_Result_i_i_fu_464_p4;

assign icmp_fu_334_p2 = ((tmp_8_fu_324_p4 == 10'd0) ? 1'b1 : 1'b0);

assign new_exp_V_1_fu_284_p2 = (new_exp_V_fu_238_p4 - shift_V_cast_cast_fu_264_p3);

assign new_exp_V_fu_238_p4 = {{p_Val2_s_fu_226_p1[62:52]}};

assign new_mant_V_1_fu_625_p14 = {{{{{{{{{{{{{q_chunk_V_ret2_i_i_reg_682}, {q_chunk_V_ret2_1_i_i_reg_687}}, {q_chunk_V_ret2_2_i_i_reg_692}}, {q_chunk_V_ret2_3_i_i_reg_697}}, {q_chunk_V_ret2_4_i_i_reg_702}}, {grp_lut_div3_chunk_fu_127_ap_return_0}}, {grp_lut_div3_chunk_fu_134_ap_return_0}}, {grp_lut_div3_chunk_fu_140_ap_return_0}}, {grp_lut_div3_chunk_fu_146_ap_return_0}}, {grp_lut_div3_chunk_fu_152_ap_return_0}}, {grp_lut_div3_chunk_fu_158_ap_return_0}}, {call_ret4_10_i_i_lut_div3_chunk_fu_164_ap_return_0}}, {call_ret4_11_i_i_lut_div3_chunk_fu_170_ap_return_0}};

assign new_mant_V_fu_248_p1 = p_Val2_s_fu_226_p1[51:0];

assign p_Repl2_1_fu_304_p3 = ((tmp_7_fu_298_p2[0:0] === 1'b1) ? p_new_exp_V_1_fu_290_p3 : new_exp_V_1_fu_284_p2);

assign p_Result_i_i_fu_464_p4 = {{xf_V_fu_458_p2[54:52]}};

assign p_Result_s_fu_651_p4 = {{{p_Repl2_2_reg_663}, {p_Repl2_1_reg_677}}, {ap_phi_mux_p_Repl2_s_phi_fu_121_p4}};

assign p_Val2_s_fu_226_p1 = in_r;

assign p_cast_fu_422_p1 = xf_V_1_fu_414_p3;

assign p_new_exp_V_1_fu_290_p3 = ((tmp_1_fu_272_p2[0:0] === 1'b1) ? 11'd2047 : 11'd0);

assign r_V_1_cast_fu_440_p1 = r_V_3_fu_434_p2;

assign r_V_3_fu_434_p2 = xf_V_1_fu_414_p3 >> tmp_cast_fu_430_p1;

assign r_V_4_fu_444_p2 = p_cast_fu_422_p1 << tmp_s_fu_426_p1;

assign sel_tmp3_demorgan_fu_352_p2 = (tmp_5_fu_318_p2 | tmp_4_fu_312_p2);

assign sel_tmp3_fu_358_p2 = (sel_tmp3_demorgan_fu_352_p2 ^ 1'd1);

assign sel_tmp4_fu_364_p2 = (sel_tmp3_fu_358_p2 & icmp_fu_334_p2);

assign sel_tmp7_fu_386_p2 = (tmp_4_fu_312_p2 ^ 1'd1);

assign sel_tmp8_fu_392_p2 = (tmp_5_fu_318_p2 & sel_tmp7_fu_386_p2);

assign shift_V_1_fu_346_p2 = ($signed(11'd2047) + $signed(new_exp_V_fu_238_p4));

assign shift_V_2_fu_370_p3 = ((sel_tmp4_fu_364_p2[0:0] === 1'b1) ? shift_V_fu_340_p2 : shift_V_1_fu_346_p2);

assign shift_V_3_fu_378_p3 = ((tmp_4_fu_312_p2[0:0] === 1'b1) ? 11'd0 : shift_V_2_fu_370_p3);

assign shift_V_4_fu_398_p3 = ((sel_tmp8_fu_392_p2[0:0] === 1'b1) ? shift_V_cast_cast_fu_264_p3 : shift_V_3_fu_378_p3);

assign shift_V_cast_cast_fu_264_p3 = ((tmp_fu_256_p3[0:0] === 1'b1) ? 11'd1 : 11'd2);

assign shift_V_fu_340_p2 = (11'd1 - new_exp_V_fu_238_p4);

assign tmp_1_fu_272_p2 = ((new_exp_V_fu_238_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign tmp_2_fu_278_p2 = ((shift_V_cast_cast_fu_264_p3 > new_exp_V_fu_238_p4) ? 1'b1 : 1'b0);

assign tmp_3_fu_406_p3 = {{1'd1}, {new_mant_V_fu_248_p1}};

assign tmp_4_fu_312_p2 = ((new_exp_V_fu_238_p4 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_5_fu_318_p2 = ((shift_V_cast_cast_fu_264_p3 < new_exp_V_fu_238_p4) ? 1'b1 : 1'b0);

assign tmp_7_fu_298_p2 = (tmp_2_fu_278_p2 | tmp_1_fu_272_p2);

assign tmp_8_fu_324_p4 = {{p_Val2_s_fu_226_p1[62:53]}};

assign tmp_9_fu_604_p1 = xf_V_fu_458_p2[3:0];

assign tmp_cast_fu_430_p1 = shift_V_4_fu_398_p3;

assign tmp_fu_256_p3 = p_Val2_s_fu_226_p1[32'd51];

assign tmp_s_fu_426_p1 = shift_V_4_fu_398_p3;

assign xf_V_1_fu_414_p3 = ((tmp_4_fu_312_p2[0:0] === 1'b1) ? xf_V_5_cast_fu_252_p1 : tmp_3_fu_406_p3);

assign xf_V_3_fu_450_p3 = ((icmp_fu_334_p2[0:0] === 1'b1) ? r_V_1_cast_fu_440_p1 : r_V_4_fu_444_p2);

assign xf_V_5_cast_fu_252_p1 = new_mant_V_fu_248_p1;

assign xf_V_fu_458_p2 = (55'd1 + xf_V_3_fu_450_p3);

endmodule //operator_double_div3
