// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module int_64_div11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] in_V;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1:0] q_chunk_V_reg_895;
reg   [1:0] q_chunk_V_0_1_reg_900;
reg   [1:0] q_chunk_V_0_2_reg_905;
reg   [1:0] q_chunk_V_0_3_reg_910;
reg   [1:0] q_chunk_V_0_4_reg_915;
reg   [1:0] q_chunk_V_0_5_reg_920;
reg   [1:0] q_chunk_V_0_6_reg_925;
reg   [3:0] r_V_ret_6_reg_930;
reg   [1:0] p_Result_13_7_reg_935;
reg   [1:0] p_Result_13_8_reg_940;
reg   [1:0] p_Result_13_9_reg_945;
reg   [1:0] p_Result_13_s_reg_950;
reg   [1:0] p_Result_13_10_reg_955;
reg   [1:0] p_Result_13_11_reg_960;
reg   [1:0] p_Result_13_12_reg_965;
reg   [1:0] p_Result_13_13_reg_970;
reg   [1:0] p_Result_13_14_reg_975;
reg   [1:0] p_Result_13_15_reg_980;
reg   [1:0] p_Result_13_16_reg_985;
reg   [1:0] p_Result_13_17_reg_990;
reg   [1:0] p_Result_13_18_reg_995;
reg   [1:0] p_Result_13_19_reg_1000;
reg   [1:0] p_Result_13_20_reg_1005;
reg   [1:0] p_Result_13_21_reg_1010;
reg   [1:0] p_Result_13_22_reg_1015;
reg   [1:0] p_Result_13_23_reg_1020;
reg   [1:0] p_Result_13_24_reg_1025;
reg   [1:0] p_Result_13_25_reg_1030;
reg   [1:0] p_Result_13_26_reg_1035;
reg   [1:0] p_Result_13_27_reg_1040;
reg   [1:0] p_Result_13_28_reg_1045;
reg   [1:0] p_Result_13_29_reg_1050;
wire   [1:0] tmp_fu_673_p1;
reg   [1:0] tmp_reg_1055;
wire    grp_lut_div11_chunk_fu_142_ap_ready;
reg   [1:0] grp_lut_div11_chunk_fu_142_d_V;
reg   [3:0] grp_lut_div11_chunk_fu_142_r_in_V;
wire   [1:0] grp_lut_div11_chunk_fu_142_ap_return_0;
wire   [3:0] grp_lut_div11_chunk_fu_142_ap_return_1;
wire    grp_lut_div11_chunk_fu_149_ap_ready;
reg   [1:0] grp_lut_div11_chunk_fu_149_d_V;
wire   [1:0] grp_lut_div11_chunk_fu_149_ap_return_0;
wire   [3:0] grp_lut_div11_chunk_fu_149_ap_return_1;
wire    grp_lut_div11_chunk_fu_155_ap_ready;
reg   [1:0] grp_lut_div11_chunk_fu_155_d_V;
wire   [1:0] grp_lut_div11_chunk_fu_155_ap_return_0;
wire   [3:0] grp_lut_div11_chunk_fu_155_ap_return_1;
wire    grp_lut_div11_chunk_fu_161_ap_ready;
reg   [1:0] grp_lut_div11_chunk_fu_161_d_V;
wire   [1:0] grp_lut_div11_chunk_fu_161_ap_return_0;
wire   [3:0] grp_lut_div11_chunk_fu_161_ap_return_1;
wire    grp_lut_div11_chunk_fu_167_ap_ready;
reg   [1:0] grp_lut_div11_chunk_fu_167_d_V;
wire   [1:0] grp_lut_div11_chunk_fu_167_ap_return_0;
wire   [3:0] grp_lut_div11_chunk_fu_167_ap_return_1;
wire    grp_lut_div11_chunk_fu_173_ap_ready;
reg   [1:0] grp_lut_div11_chunk_fu_173_d_V;
wire   [1:0] grp_lut_div11_chunk_fu_173_ap_return_0;
wire   [3:0] grp_lut_div11_chunk_fu_173_ap_return_1;
wire    grp_lut_div11_chunk_fu_179_ap_ready;
reg   [1:0] grp_lut_div11_chunk_fu_179_d_V;
wire   [1:0] grp_lut_div11_chunk_fu_179_ap_return_0;
wire   [3:0] grp_lut_div11_chunk_fu_179_ap_return_1;
wire    call_ret_13_lut_div11_chunk_fu_185_ap_ready;
wire   [1:0] call_ret_13_lut_div11_chunk_fu_185_ap_return_0;
wire   [3:0] call_ret_13_lut_div11_chunk_fu_185_ap_return_1;
wire    call_ret_14_lut_div11_chunk_fu_191_ap_ready;
wire   [1:0] call_ret_14_lut_div11_chunk_fu_191_ap_return_0;
wire   [3:0] call_ret_14_lut_div11_chunk_fu_191_ap_return_1;
wire    call_ret_15_lut_div11_chunk_fu_197_ap_ready;
wire   [1:0] call_ret_15_lut_div11_chunk_fu_197_ap_return_0;
wire   [3:0] call_ret_15_lut_div11_chunk_fu_197_ap_return_1;
wire    call_ret_16_lut_div11_chunk_fu_203_ap_ready;
wire   [1:0] call_ret_16_lut_div11_chunk_fu_203_ap_return_0;
wire   [3:0] call_ret_16_lut_div11_chunk_fu_203_ap_return_1;
wire    call_ret_17_lut_div11_chunk_fu_209_ap_ready;
wire   [1:0] call_ret_17_lut_div11_chunk_fu_209_ap_return_0;
wire   [3:0] call_ret_17_lut_div11_chunk_fu_209_ap_return_1;
wire    call_ret_18_lut_div11_chunk_fu_215_ap_ready;
wire   [1:0] call_ret_18_lut_div11_chunk_fu_215_ap_return_0;
wire   [3:0] call_ret_18_lut_div11_chunk_fu_215_ap_return_1;
wire    call_ret_19_lut_div11_chunk_fu_221_ap_ready;
wire   [1:0] call_ret_19_lut_div11_chunk_fu_221_ap_return_0;
wire   [3:0] call_ret_19_lut_div11_chunk_fu_221_ap_return_1;
wire    call_ret_20_lut_div11_chunk_fu_227_ap_ready;
wire   [1:0] call_ret_20_lut_div11_chunk_fu_227_ap_return_0;
wire   [3:0] call_ret_20_lut_div11_chunk_fu_227_ap_return_1;
wire    call_ret_21_lut_div11_chunk_fu_233_ap_ready;
wire   [1:0] call_ret_21_lut_div11_chunk_fu_233_ap_return_0;
wire   [3:0] call_ret_21_lut_div11_chunk_fu_233_ap_return_1;
wire    call_ret_22_lut_div11_chunk_fu_239_ap_ready;
wire   [1:0] call_ret_22_lut_div11_chunk_fu_239_ap_return_0;
wire   [3:0] call_ret_22_lut_div11_chunk_fu_239_ap_return_1;
wire    call_ret_23_lut_div11_chunk_fu_245_ap_ready;
wire   [1:0] call_ret_23_lut_div11_chunk_fu_245_ap_return_0;
wire   [3:0] call_ret_23_lut_div11_chunk_fu_245_ap_return_1;
wire    call_ret_24_lut_div11_chunk_fu_251_ap_ready;
wire   [1:0] call_ret_24_lut_div11_chunk_fu_251_ap_return_0;
wire   [3:0] call_ret_24_lut_div11_chunk_fu_251_ap_return_1;
wire    call_ret_25_lut_div11_chunk_fu_257_ap_ready;
wire   [1:0] call_ret_25_lut_div11_chunk_fu_257_ap_return_0;
wire   [3:0] call_ret_25_lut_div11_chunk_fu_257_ap_return_1;
wire    call_ret_26_lut_div11_chunk_fu_263_ap_ready;
wire   [1:0] call_ret_26_lut_div11_chunk_fu_263_ap_return_0;
wire   [3:0] call_ret_26_lut_div11_chunk_fu_263_ap_return_1;
wire    call_ret_27_lut_div11_chunk_fu_269_ap_ready;
wire   [1:0] call_ret_27_lut_div11_chunk_fu_269_ap_return_0;
wire   [3:0] call_ret_27_lut_div11_chunk_fu_269_ap_return_1;
wire    call_ret_28_lut_div11_chunk_fu_275_ap_ready;
wire   [1:0] call_ret_28_lut_div11_chunk_fu_275_ap_return_0;
wire   [3:0] call_ret_28_lut_div11_chunk_fu_275_ap_return_1;
wire    call_ret_29_lut_div11_chunk_fu_281_ap_ready;
wire   [1:0] call_ret_29_lut_div11_chunk_fu_281_ap_return_0;
wire   [3:0] call_ret_29_lut_div11_chunk_fu_281_ap_return_1;
wire    call_ret_30_lut_div11_chunk_fu_287_ap_ready;
wire   [1:0] call_ret_30_lut_div11_chunk_fu_287_ap_return_0;
wire   [3:0] call_ret_30_lut_div11_chunk_fu_287_ap_return_1;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

lut_div11_chunk grp_lut_div11_chunk_fu_142(
    .ap_ready(grp_lut_div11_chunk_fu_142_ap_ready),
    .d_V(grp_lut_div11_chunk_fu_142_d_V),
    .r_in_V(grp_lut_div11_chunk_fu_142_r_in_V),
    .ap_return_0(grp_lut_div11_chunk_fu_142_ap_return_0),
    .ap_return_1(grp_lut_div11_chunk_fu_142_ap_return_1)
);

lut_div11_chunk grp_lut_div11_chunk_fu_149(
    .ap_ready(grp_lut_div11_chunk_fu_149_ap_ready),
    .d_V(grp_lut_div11_chunk_fu_149_d_V),
    .r_in_V(grp_lut_div11_chunk_fu_142_ap_return_1),
    .ap_return_0(grp_lut_div11_chunk_fu_149_ap_return_0),
    .ap_return_1(grp_lut_div11_chunk_fu_149_ap_return_1)
);

lut_div11_chunk grp_lut_div11_chunk_fu_155(
    .ap_ready(grp_lut_div11_chunk_fu_155_ap_ready),
    .d_V(grp_lut_div11_chunk_fu_155_d_V),
    .r_in_V(grp_lut_div11_chunk_fu_149_ap_return_1),
    .ap_return_0(grp_lut_div11_chunk_fu_155_ap_return_0),
    .ap_return_1(grp_lut_div11_chunk_fu_155_ap_return_1)
);

lut_div11_chunk grp_lut_div11_chunk_fu_161(
    .ap_ready(grp_lut_div11_chunk_fu_161_ap_ready),
    .d_V(grp_lut_div11_chunk_fu_161_d_V),
    .r_in_V(grp_lut_div11_chunk_fu_155_ap_return_1),
    .ap_return_0(grp_lut_div11_chunk_fu_161_ap_return_0),
    .ap_return_1(grp_lut_div11_chunk_fu_161_ap_return_1)
);

lut_div11_chunk grp_lut_div11_chunk_fu_167(
    .ap_ready(grp_lut_div11_chunk_fu_167_ap_ready),
    .d_V(grp_lut_div11_chunk_fu_167_d_V),
    .r_in_V(grp_lut_div11_chunk_fu_161_ap_return_1),
    .ap_return_0(grp_lut_div11_chunk_fu_167_ap_return_0),
    .ap_return_1(grp_lut_div11_chunk_fu_167_ap_return_1)
);

lut_div11_chunk grp_lut_div11_chunk_fu_173(
    .ap_ready(grp_lut_div11_chunk_fu_173_ap_ready),
    .d_V(grp_lut_div11_chunk_fu_173_d_V),
    .r_in_V(grp_lut_div11_chunk_fu_167_ap_return_1),
    .ap_return_0(grp_lut_div11_chunk_fu_173_ap_return_0),
    .ap_return_1(grp_lut_div11_chunk_fu_173_ap_return_1)
);

lut_div11_chunk grp_lut_div11_chunk_fu_179(
    .ap_ready(grp_lut_div11_chunk_fu_179_ap_ready),
    .d_V(grp_lut_div11_chunk_fu_179_d_V),
    .r_in_V(grp_lut_div11_chunk_fu_173_ap_return_1),
    .ap_return_0(grp_lut_div11_chunk_fu_179_ap_return_0),
    .ap_return_1(grp_lut_div11_chunk_fu_179_ap_return_1)
);

lut_div11_chunk call_ret_13_lut_div11_chunk_fu_185(
    .ap_ready(call_ret_13_lut_div11_chunk_fu_185_ap_ready),
    .d_V(p_Result_13_13_reg_970),
    .r_in_V(grp_lut_div11_chunk_fu_179_ap_return_1),
    .ap_return_0(call_ret_13_lut_div11_chunk_fu_185_ap_return_0),
    .ap_return_1(call_ret_13_lut_div11_chunk_fu_185_ap_return_1)
);

lut_div11_chunk call_ret_14_lut_div11_chunk_fu_191(
    .ap_ready(call_ret_14_lut_div11_chunk_fu_191_ap_ready),
    .d_V(p_Result_13_14_reg_975),
    .r_in_V(call_ret_13_lut_div11_chunk_fu_185_ap_return_1),
    .ap_return_0(call_ret_14_lut_div11_chunk_fu_191_ap_return_0),
    .ap_return_1(call_ret_14_lut_div11_chunk_fu_191_ap_return_1)
);

lut_div11_chunk call_ret_15_lut_div11_chunk_fu_197(
    .ap_ready(call_ret_15_lut_div11_chunk_fu_197_ap_ready),
    .d_V(p_Result_13_15_reg_980),
    .r_in_V(call_ret_14_lut_div11_chunk_fu_191_ap_return_1),
    .ap_return_0(call_ret_15_lut_div11_chunk_fu_197_ap_return_0),
    .ap_return_1(call_ret_15_lut_div11_chunk_fu_197_ap_return_1)
);

lut_div11_chunk call_ret_16_lut_div11_chunk_fu_203(
    .ap_ready(call_ret_16_lut_div11_chunk_fu_203_ap_ready),
    .d_V(p_Result_13_16_reg_985),
    .r_in_V(call_ret_15_lut_div11_chunk_fu_197_ap_return_1),
    .ap_return_0(call_ret_16_lut_div11_chunk_fu_203_ap_return_0),
    .ap_return_1(call_ret_16_lut_div11_chunk_fu_203_ap_return_1)
);

lut_div11_chunk call_ret_17_lut_div11_chunk_fu_209(
    .ap_ready(call_ret_17_lut_div11_chunk_fu_209_ap_ready),
    .d_V(p_Result_13_17_reg_990),
    .r_in_V(call_ret_16_lut_div11_chunk_fu_203_ap_return_1),
    .ap_return_0(call_ret_17_lut_div11_chunk_fu_209_ap_return_0),
    .ap_return_1(call_ret_17_lut_div11_chunk_fu_209_ap_return_1)
);

lut_div11_chunk call_ret_18_lut_div11_chunk_fu_215(
    .ap_ready(call_ret_18_lut_div11_chunk_fu_215_ap_ready),
    .d_V(p_Result_13_18_reg_995),
    .r_in_V(call_ret_17_lut_div11_chunk_fu_209_ap_return_1),
    .ap_return_0(call_ret_18_lut_div11_chunk_fu_215_ap_return_0),
    .ap_return_1(call_ret_18_lut_div11_chunk_fu_215_ap_return_1)
);

lut_div11_chunk call_ret_19_lut_div11_chunk_fu_221(
    .ap_ready(call_ret_19_lut_div11_chunk_fu_221_ap_ready),
    .d_V(p_Result_13_19_reg_1000),
    .r_in_V(call_ret_18_lut_div11_chunk_fu_215_ap_return_1),
    .ap_return_0(call_ret_19_lut_div11_chunk_fu_221_ap_return_0),
    .ap_return_1(call_ret_19_lut_div11_chunk_fu_221_ap_return_1)
);

lut_div11_chunk call_ret_20_lut_div11_chunk_fu_227(
    .ap_ready(call_ret_20_lut_div11_chunk_fu_227_ap_ready),
    .d_V(p_Result_13_20_reg_1005),
    .r_in_V(call_ret_19_lut_div11_chunk_fu_221_ap_return_1),
    .ap_return_0(call_ret_20_lut_div11_chunk_fu_227_ap_return_0),
    .ap_return_1(call_ret_20_lut_div11_chunk_fu_227_ap_return_1)
);

lut_div11_chunk call_ret_21_lut_div11_chunk_fu_233(
    .ap_ready(call_ret_21_lut_div11_chunk_fu_233_ap_ready),
    .d_V(p_Result_13_21_reg_1010),
    .r_in_V(call_ret_20_lut_div11_chunk_fu_227_ap_return_1),
    .ap_return_0(call_ret_21_lut_div11_chunk_fu_233_ap_return_0),
    .ap_return_1(call_ret_21_lut_div11_chunk_fu_233_ap_return_1)
);

lut_div11_chunk call_ret_22_lut_div11_chunk_fu_239(
    .ap_ready(call_ret_22_lut_div11_chunk_fu_239_ap_ready),
    .d_V(p_Result_13_22_reg_1015),
    .r_in_V(call_ret_21_lut_div11_chunk_fu_233_ap_return_1),
    .ap_return_0(call_ret_22_lut_div11_chunk_fu_239_ap_return_0),
    .ap_return_1(call_ret_22_lut_div11_chunk_fu_239_ap_return_1)
);

lut_div11_chunk call_ret_23_lut_div11_chunk_fu_245(
    .ap_ready(call_ret_23_lut_div11_chunk_fu_245_ap_ready),
    .d_V(p_Result_13_23_reg_1020),
    .r_in_V(call_ret_22_lut_div11_chunk_fu_239_ap_return_1),
    .ap_return_0(call_ret_23_lut_div11_chunk_fu_245_ap_return_0),
    .ap_return_1(call_ret_23_lut_div11_chunk_fu_245_ap_return_1)
);

lut_div11_chunk call_ret_24_lut_div11_chunk_fu_251(
    .ap_ready(call_ret_24_lut_div11_chunk_fu_251_ap_ready),
    .d_V(p_Result_13_24_reg_1025),
    .r_in_V(call_ret_23_lut_div11_chunk_fu_245_ap_return_1),
    .ap_return_0(call_ret_24_lut_div11_chunk_fu_251_ap_return_0),
    .ap_return_1(call_ret_24_lut_div11_chunk_fu_251_ap_return_1)
);

lut_div11_chunk call_ret_25_lut_div11_chunk_fu_257(
    .ap_ready(call_ret_25_lut_div11_chunk_fu_257_ap_ready),
    .d_V(p_Result_13_25_reg_1030),
    .r_in_V(call_ret_24_lut_div11_chunk_fu_251_ap_return_1),
    .ap_return_0(call_ret_25_lut_div11_chunk_fu_257_ap_return_0),
    .ap_return_1(call_ret_25_lut_div11_chunk_fu_257_ap_return_1)
);

lut_div11_chunk call_ret_26_lut_div11_chunk_fu_263(
    .ap_ready(call_ret_26_lut_div11_chunk_fu_263_ap_ready),
    .d_V(p_Result_13_26_reg_1035),
    .r_in_V(call_ret_25_lut_div11_chunk_fu_257_ap_return_1),
    .ap_return_0(call_ret_26_lut_div11_chunk_fu_263_ap_return_0),
    .ap_return_1(call_ret_26_lut_div11_chunk_fu_263_ap_return_1)
);

lut_div11_chunk call_ret_27_lut_div11_chunk_fu_269(
    .ap_ready(call_ret_27_lut_div11_chunk_fu_269_ap_ready),
    .d_V(p_Result_13_27_reg_1040),
    .r_in_V(call_ret_26_lut_div11_chunk_fu_263_ap_return_1),
    .ap_return_0(call_ret_27_lut_div11_chunk_fu_269_ap_return_0),
    .ap_return_1(call_ret_27_lut_div11_chunk_fu_269_ap_return_1)
);

lut_div11_chunk call_ret_28_lut_div11_chunk_fu_275(
    .ap_ready(call_ret_28_lut_div11_chunk_fu_275_ap_ready),
    .d_V(p_Result_13_28_reg_1045),
    .r_in_V(call_ret_27_lut_div11_chunk_fu_269_ap_return_1),
    .ap_return_0(call_ret_28_lut_div11_chunk_fu_275_ap_return_0),
    .ap_return_1(call_ret_28_lut_div11_chunk_fu_275_ap_return_1)
);

lut_div11_chunk call_ret_29_lut_div11_chunk_fu_281(
    .ap_ready(call_ret_29_lut_div11_chunk_fu_281_ap_ready),
    .d_V(p_Result_13_29_reg_1050),
    .r_in_V(call_ret_28_lut_div11_chunk_fu_275_ap_return_1),
    .ap_return_0(call_ret_29_lut_div11_chunk_fu_281_ap_return_0),
    .ap_return_1(call_ret_29_lut_div11_chunk_fu_281_ap_return_1)
);

lut_div11_chunk call_ret_30_lut_div11_chunk_fu_287(
    .ap_ready(call_ret_30_lut_div11_chunk_fu_287_ap_ready),
    .d_V(tmp_reg_1055),
    .r_in_V(call_ret_29_lut_div11_chunk_fu_281_ap_return_1),
    .ap_return_0(call_ret_30_lut_div11_chunk_fu_287_ap_return_0),
    .ap_return_1(call_ret_30_lut_div11_chunk_fu_287_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_Result_13_10_reg_955 <= {{in_V[41:40]}};
        p_Result_13_11_reg_960 <= {{in_V[39:38]}};
        p_Result_13_12_reg_965 <= {{in_V[37:36]}};
        p_Result_13_13_reg_970 <= {{in_V[35:34]}};
        p_Result_13_14_reg_975 <= {{in_V[33:32]}};
        p_Result_13_15_reg_980 <= {{in_V[31:30]}};
        p_Result_13_16_reg_985 <= {{in_V[29:28]}};
        p_Result_13_17_reg_990 <= {{in_V[27:26]}};
        p_Result_13_18_reg_995 <= {{in_V[25:24]}};
        p_Result_13_19_reg_1000 <= {{in_V[23:22]}};
        p_Result_13_20_reg_1005 <= {{in_V[21:20]}};
        p_Result_13_21_reg_1010 <= {{in_V[19:18]}};
        p_Result_13_22_reg_1015 <= {{in_V[17:16]}};
        p_Result_13_23_reg_1020 <= {{in_V[15:14]}};
        p_Result_13_24_reg_1025 <= {{in_V[13:12]}};
        p_Result_13_25_reg_1030 <= {{in_V[11:10]}};
        p_Result_13_26_reg_1035 <= {{in_V[9:8]}};
        p_Result_13_27_reg_1040 <= {{in_V[7:6]}};
        p_Result_13_28_reg_1045 <= {{in_V[5:4]}};
        p_Result_13_29_reg_1050 <= {{in_V[3:2]}};
        p_Result_13_7_reg_935 <= {{in_V[49:48]}};
        p_Result_13_8_reg_940 <= {{in_V[47:46]}};
        p_Result_13_9_reg_945 <= {{in_V[45:44]}};
        p_Result_13_s_reg_950 <= {{in_V[43:42]}};
        q_chunk_V_0_1_reg_900 <= grp_lut_div11_chunk_fu_149_ap_return_0;
        q_chunk_V_0_2_reg_905 <= grp_lut_div11_chunk_fu_155_ap_return_0;
        q_chunk_V_0_3_reg_910 <= grp_lut_div11_chunk_fu_161_ap_return_0;
        q_chunk_V_0_4_reg_915 <= grp_lut_div11_chunk_fu_167_ap_return_0;
        q_chunk_V_0_5_reg_920 <= grp_lut_div11_chunk_fu_173_ap_return_0;
        q_chunk_V_0_6_reg_925 <= grp_lut_div11_chunk_fu_179_ap_return_0;
        q_chunk_V_reg_895 <= grp_lut_div11_chunk_fu_142_ap_return_0;
        r_V_ret_6_reg_930 <= grp_lut_div11_chunk_fu_179_ap_return_1;
        tmp_reg_1055 <= tmp_fu_673_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_lut_div11_chunk_fu_142_d_V = p_Result_13_7_reg_935;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_lut_div11_chunk_fu_142_d_V = {{in_V[63:62]}};
    end else begin
        grp_lut_div11_chunk_fu_142_d_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_lut_div11_chunk_fu_142_r_in_V = r_V_ret_6_reg_930;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_lut_div11_chunk_fu_142_r_in_V = 4'd0;
    end else begin
        grp_lut_div11_chunk_fu_142_r_in_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_lut_div11_chunk_fu_149_d_V = p_Result_13_8_reg_940;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_lut_div11_chunk_fu_149_d_V = {{in_V[61:60]}};
    end else begin
        grp_lut_div11_chunk_fu_149_d_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_lut_div11_chunk_fu_155_d_V = p_Result_13_9_reg_945;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_lut_div11_chunk_fu_155_d_V = {{in_V[59:58]}};
    end else begin
        grp_lut_div11_chunk_fu_155_d_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_lut_div11_chunk_fu_161_d_V = p_Result_13_s_reg_950;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_lut_div11_chunk_fu_161_d_V = {{in_V[57:56]}};
    end else begin
        grp_lut_div11_chunk_fu_161_d_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_lut_div11_chunk_fu_167_d_V = p_Result_13_10_reg_955;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_lut_div11_chunk_fu_167_d_V = {{in_V[55:54]}};
    end else begin
        grp_lut_div11_chunk_fu_167_d_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_lut_div11_chunk_fu_173_d_V = p_Result_13_11_reg_960;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_lut_div11_chunk_fu_173_d_V = {{in_V[53:52]}};
    end else begin
        grp_lut_div11_chunk_fu_173_d_V = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_lut_div11_chunk_fu_179_d_V = p_Result_13_12_reg_965;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_lut_div11_chunk_fu_179_d_V = {{in_V[51:50]}};
    end else begin
        grp_lut_div11_chunk_fu_179_d_V = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{q_chunk_V_reg_895}, {q_chunk_V_0_1_reg_900}}, {q_chunk_V_0_2_reg_905}}, {q_chunk_V_0_3_reg_910}}, {q_chunk_V_0_4_reg_915}}, {q_chunk_V_0_5_reg_920}}, {q_chunk_V_0_6_reg_925}}, {grp_lut_div11_chunk_fu_142_ap_return_0}}, {grp_lut_div11_chunk_fu_149_ap_return_0}}, {grp_lut_div11_chunk_fu_155_ap_return_0}}, {grp_lut_div11_chunk_fu_161_ap_return_0}}, {grp_lut_div11_chunk_fu_167_ap_return_0}}, {grp_lut_div11_chunk_fu_173_ap_return_0}}, {grp_lut_div11_chunk_fu_179_ap_return_0}}, {call_ret_13_lut_div11_chunk_fu_185_ap_return_0}}, {call_ret_14_lut_div11_chunk_fu_191_ap_return_0}}, {call_ret_15_lut_div11_chunk_fu_197_ap_return_0}}, {call_ret_16_lut_div11_chunk_fu_203_ap_return_0}}, {call_ret_17_lut_div11_chunk_fu_209_ap_return_0}}, {call_ret_18_lut_div11_chunk_fu_215_ap_return_0}}, {call_ret_19_lut_div11_chunk_fu_221_ap_return_0}}, {call_ret_20_lut_div11_chunk_fu_227_ap_return_0}}, {call_ret_21_lut_div11_chunk_fu_233_ap_return_0}}, {call_ret_22_lut_div11_chunk_fu_239_ap_return_0}}, {call_ret_23_lut_div11_chunk_fu_245_ap_return_0}}, {call_ret_24_lut_div11_chunk_fu_251_ap_return_0}}, {call_ret_25_lut_div11_chunk_fu_257_ap_return_0}}, {call_ret_26_lut_div11_chunk_fu_263_ap_return_0}}, {call_ret_27_lut_div11_chunk_fu_269_ap_return_0}}, {call_ret_28_lut_div11_chunk_fu_275_ap_return_0}}, {call_ret_29_lut_div11_chunk_fu_281_ap_return_0}}, {call_ret_30_lut_div11_chunk_fu_287_ap_return_0}};

assign tmp_fu_673_p1 = in_V[1:0];

endmodule //int_64_div11
