// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "div6.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic div6::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic div6::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> div6::ap_ST_fsm_state1 = "1";
const sc_lv<2> div6::ap_ST_fsm_state2 = "10";
const sc_lv<32> div6::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<129> div6::ap_const_lv129_lc_3 = "10101010101010101010101010101010101010101010101010101010101010110";
const sc_lv<32> div6::ap_const_lv32_3F = "111111";
const sc_lv<129> div6::ap_const_lv129_lc_2 = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> div6::ap_const_lv32_1 = "1";
const sc_lv<32> div6::ap_const_lv32_43 = "1000011";
const sc_lv<32> div6::ap_const_lv32_80 = "10000000";
const sc_lv<64> div6::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const bool div6::ap_const_boolean_1 = true;

div6::div6(sc_module_name name) : sc_module(name), mVcdFile(0) {
    div6_mul_64s_66nsbkb_U1 = new div6_mul_64s_66nsbkb<1,2,64,66,129>("div6_mul_64s_66nsbkb_U1");
    div6_mul_64s_66nsbkb_U1->clk(ap_clk);
    div6_mul_64s_66nsbkb_U1->reset(ap_rst);
    div6_mul_64s_66nsbkb_U1->din0(a);
    div6_mul_64s_66nsbkb_U1->din1(grp_fu_44_p1);
    div6_mul_64s_66nsbkb_U1->ce(ap_var_for_const0);
    div6_mul_64s_66nsbkb_U1->dout(grp_fu_44_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_4_reg_117 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_2_fu_88_p1 );
    sensitive << ( neg_ti_fu_99_p2 );

    SC_METHOD(thread_grp_fu_44_p1);
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_neg_mul_fu_58_p2);
    sensitive << ( grp_fu_44_p2 );

    SC_METHOD(thread_neg_ti_fu_99_p2);
    sensitive << ( tmp_3_fu_92_p3 );

    SC_METHOD(thread_tmp_1_fu_74_p1);
    sensitive << ( tmp_5_fu_64_p4 );

    SC_METHOD(thread_tmp_2_fu_88_p1);
    sensitive << ( tmp_6_fu_78_p4 );

    SC_METHOD(thread_tmp_3_fu_92_p3);
    sensitive << ( tmp_4_reg_117 );
    sensitive << ( tmp_1_fu_74_p1 );
    sensitive << ( tmp_2_fu_88_p1 );

    SC_METHOD(thread_tmp_4_fu_50_p1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( a );

    SC_METHOD(thread_tmp_5_fu_64_p4);
    sensitive << ( neg_mul_fu_58_p2 );

    SC_METHOD(thread_tmp_6_fu_78_p4);
    sensitive << ( grp_fu_44_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "div6_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a, "(port)a");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_4_reg_117, "tmp_4_reg_117");
    sc_trace(mVcdFile, grp_fu_44_p1, "grp_fu_44_p1");
    sc_trace(mVcdFile, tmp_4_fu_50_p1, "tmp_4_fu_50_p1");
    sc_trace(mVcdFile, grp_fu_44_p2, "grp_fu_44_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, neg_mul_fu_58_p2, "neg_mul_fu_58_p2");
    sc_trace(mVcdFile, tmp_5_fu_64_p4, "tmp_5_fu_64_p4");
    sc_trace(mVcdFile, tmp_6_fu_78_p4, "tmp_6_fu_78_p4");
    sc_trace(mVcdFile, tmp_1_fu_74_p1, "tmp_1_fu_74_p1");
    sc_trace(mVcdFile, tmp_2_fu_88_p1, "tmp_2_fu_88_p1");
    sc_trace(mVcdFile, tmp_3_fu_92_p3, "tmp_3_fu_92_p3");
    sc_trace(mVcdFile, neg_ti_fu_99_p2, "neg_ti_fu_99_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("div6.hdltvin.dat");
    mHdltvoutHandle.open("div6.hdltvout.dat");
}

div6::~div6() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete div6_mul_64s_66nsbkb_U1;
}

void div6::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void div6::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        tmp_4_reg_117 = tmp_4_fu_50_p1.read().range(63, 63);
    }
}

void div6::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void div6::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void div6::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void div6::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void div6::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void div6::thread_ap_return() {
    ap_return = (!tmp_4_reg_117.read()[0].is_01())? sc_lv<64>(): ((tmp_4_reg_117.read()[0].to_bool())? neg_ti_fu_99_p2.read(): tmp_2_fu_88_p1.read());
}

void div6::thread_grp_fu_44_p1() {
    grp_fu_44_p1 =  (sc_lv<66>) (ap_const_lv129_lc_3);
}

void div6::thread_neg_mul_fu_58_p2() {
    neg_mul_fu_58_p2 = (!ap_const_lv129_lc_2.is_01() || !grp_fu_44_p2.read().is_01())? sc_lv<129>(): (sc_biguint<129>(ap_const_lv129_lc_2) - sc_biguint<129>(grp_fu_44_p2.read()));
}

void div6::thread_neg_ti_fu_99_p2() {
    neg_ti_fu_99_p2 = (!ap_const_lv64_0.is_01() || !tmp_3_fu_92_p3.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_0) - sc_biguint<64>(tmp_3_fu_92_p3.read()));
}

void div6::thread_tmp_1_fu_74_p1() {
    tmp_1_fu_74_p1 = esl_sext<64,62>(tmp_5_fu_64_p4.read());
}

void div6::thread_tmp_2_fu_88_p1() {
    tmp_2_fu_88_p1 = esl_sext<64,62>(tmp_6_fu_78_p4.read());
}

void div6::thread_tmp_3_fu_92_p3() {
    tmp_3_fu_92_p3 = (!tmp_4_reg_117.read()[0].is_01())? sc_lv<64>(): ((tmp_4_reg_117.read()[0].to_bool())? tmp_1_fu_74_p1.read(): tmp_2_fu_88_p1.read());
}

void div6::thread_tmp_4_fu_50_p1() {
    tmp_4_fu_50_p1 = a.read();
}

void div6::thread_tmp_5_fu_64_p4() {
    tmp_5_fu_64_p4 = neg_mul_fu_58_p2.read().range(128, 67);
}

void div6::thread_tmp_6_fu_78_p4() {
    tmp_6_fu_78_p4 = grp_fu_44_p2.read().range(128, 67);
}

void div6::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void div6::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a\" :  \"" << a.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

